### ISSUE TITLE
Pre-bundling the client

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1325]
## Stage 1

- [x] eliminate use of protobufjs in config by doing `import type { Type, ... } from "protobufjs"` and move protobufjs into dev dependencies
- [x] extract PublicKey class and move it into `@dxos/protocols`
  - public-key class depends on hypercore.crypto (we should use randombytes not from hypercore)
- [x] #1340 
- [x] refactor registry client to depend on codec-protobuf
- [x] #1349 
  - including object-model, crypto packages
  - excluding model-factory
- [x] Working within Vite app

## Stage 2

- [ ] Bundling for Node
- [ ] Can we remove the need for node globals polyfill for apps?
- [ ] Split client package between backend and api in order to specifically bundle the backend
- [ ] reduce dependencies on client internals from bot-factory-client

## Notes

Currently our client has a hard time working in a vite esbuild environment. One approach is to rollup the client.

Problem packages that are causing issues:
- sodium
- protobufjs

We have our own protobuf solution: codec-protobuf. Registry client uses protobufjs to read/write records, maybe we move it into our own codec-protobuf.

Bundle at specific packages?:
- codec-protobuf

Agreed:
- lets not worry about bundling for esm for now, lets target commonjs for now
- lets bundle client without `@dxos/model-factory` and make it a dependency

Problems:
- model-factory doesnit sound like the right name for the base model: base package for model `@dxos/model` or `@dxos/model-base` or something or `@dxos/echo-model`
- codec-protobuf and crypto are deps of model-factory

Suggestions:
- maybe try bundling just the backend portion of the client? (there are two parts: api and backend portion). Can bundle it in a separate package enabling a client to connect either to a browser extension or an on-demand backend coming from CDN.
