### ISSUE TITLE
M0 Client API

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1367]
- [x] https://github.com/dxos/protocols/issues/1325
- [ ] https://github.com/dxos/protocols/issues/1300
- [x] https://github.com/dxos/protocols/issues/1232
- [x] #1368
