### ISSUE TITLE
Client Messaging

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#1472]
# TASKS

- [x] Write unite test with end-to-end messaging
- [x] Decouple messaging API from network-manager (move it to another npm package) 
- [x] Create interface for instant messaging (with .sendMessage() and .listen()) that will use Signal network
- [x] Move reliability from MessageRouter to Messenger package
- [x] Make Messenger.listen() method accept peerId, and automatically subscribe for messages
- [ ] Make SignalManager re-entrant.

# User experience
![image](https://user-images.githubusercontent.com/36420699/186669197-50629497-7c30-4985-a0c2-023f8efb0a09.png)
+buttons to add and delete contacts

@zhenyasav `s take on ```dx listen```:
_wall or write https://www.tecmint.com/send-a-message-to-logged-users-in-linux-terminal/
so if you have a terminal open anywhere it will look like another linux user messaged you
but it was actually your kube
meaning you can listen and receive messages without running anything like dx
i think this means your halo has to be running on your kube
that would be a fun addition to this feature_

# CLI commands
```bash
$ dx circle add asdvnoiascwn23e9equr8q4h
$ dx circle list
$ dx circle send <identityKey> "Hello it is the message"

# Interactive mode for sending/receiving messages.
$ dx circle listen
user-1 [online]
user-2 [online]
> user-1 Hello
< user-1 Hi!
```

# API Client/SDK
```
client.halo.circle.addContact(peerId: PublicKey): Promise<void>;
client.halo.circle.getPeerId(<snippet of peerId/username>: str) Promise<PublicKey>;
client.halo.circle.deleteContact(<snippet of peerId/username>: str): Promise<void>;
client.halo.circle.listContacts(): Promise<Contact[]>;


client.sendMessage(<snippet of peerId/username>: str, msg: str): Promise<void>;
#callback for receiving messages 
client.receiveMessage(msg: str, from: Contact): Promise<void>;
```

### Design
![architecture](https://user-images.githubusercontent.com/36420699/188156631-69d3dd70-dbae-449d-92ab-890046ba0d88.png)

# Notes

1. we have several kinds of message transport:
  - web rtc for sync
  - web rtc for ephemeral messaging
  - signaling : kubes use pub/sub to stay in sync, but kube service exposes an API
    - you can track who sends what messages to who when (not encrypted)

2. There are 3 types of messages we wanna pass through Signal network (that is the lowest level)
  - dx/rpc messages
  - invitation messages
  - bot orchestrator messages

3. Credentials for other people already exist in your echo spaces. Echo/client makes a cache of keys we can use before we have circle API ready
4. Halo is where we can add contacts we saw across parties (this is the **Circle**)

5. Let's have unit tests before we build UX

### Concerns
1. Routing is a concern. We need to route messages on some level (e.g. bot orchestrator and RPC should not receive each other's messages).
2. Reliability
3. **open issue:** to what extent is your profile available in that halo / circle (replication of profile information) at least display name.
