### ISSUE TITLE
Q4 Protocols Readiness

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#1576]
# Phase 1 
- [x] #1592
- [ ] authenticated replication
- [ ] profile username
- [ ] party properties (e.g., title)
- [ ] device list
- [ ] device preferences (e.g., label)
- [ ] offline invitations
- [ ] halo recovery (require online peer/bot)
- [ ] refactor `@dxos/feed-store`
- [ ] refactor `@dxos/client-services`

# Phase 2
- [ ] epochs/snapshots
- [ ] replace `@dxos/protocol`
- [ ] bots (integration with KUBE server)

# Technical Debt

## Misc [@wittjosiah]
- [x] #1582
- [ ] e2e testing process/plan.
- [x] replace `setImmediate` with `setTimeout` (document reason in wiki).
- [x] move `@dxos/file` into `@dxos/plate`.
- [ ] avoid using `Buffer` in types (e.g. don't depend on input parameters being `Buffer` rather then `Uint8Array`); prefer to use `PublicKey` for keys or ids.
- [ ] fix client context close error (and rename network manager close; `ERROR Signal socket error wss://halo.dxos.org/.well-known/dx/signal WebSocket was closed before the connection was established`
- [x] check `devtools` works with new stack. [@mykola-vrmchk]
- [x] consider moving `dx-cli` to `devtools` section.
- [ ] remove legacy bots packages. [@richburdon]
- [x] reorganize packages (move all protocol folders under "core").
- [ ] Clean up async (2 kinds of trigger, latch, waitUntil, etc.)
- [x] set up prettier and eslint integration so they play nice
- [ ] validate version ranges being used in package.json files (should be able to use syncpack) 

## Tools
- [x] fix logger sourcemap/line numbers. [@dmaretskyi]
- [ ] normalize `tsconfig.json` properties (esp. types, libs).
- [ ] normalize JSON files (see x deps tool), READMEs, etc. [@richburdon]
- [ ] reset npm package deployments; make private unless required externally. [@zhenyasav]
- [ ] remove `@dxos/protocols-toolchain`.
- [ ] protobuf lint tool.

## `@dxos/credentials` [@dmaretskyi]
- [x] maintain package name but replace with `@dxos/halo-protocol` code.

## `@dxos/protocol` [@dmaretskyi]
- [ ] MESH rewrite.
- [ ] remove custom fork "hypercore-protocol": "dxos/hypercore-protocol#05513f9266f8bec4d29b144b72c59257c2d7bd60",
  - [ ] deprecate/remove: https://github.com/dxos/simple-hypercore-protocol/settings (fixed in simple-hypercore-protocol@2.1.2)

## `@dxos/crypto` [@dmaretskyi]
- [ ] move crypto utils to `@dxos/crypto`.
- [ ] Remove unused functions.
- [ ] Minimize dependency on third-party crypto libraries.
- [x] remove dep on `dxos/protocols`.
- [ ] remove createId (echo-db).

## `@dxos/echo-db` [@dmaretskyi]
- [x] Fix mock imports.
- [x] Remove dead code.
- [ ] Refactor database integration: currently space class directly depends on a specific database implementation - make specific database be injected into the space class implementation.
- [x] Remove `@dxos/echo-protocol`.

## `@dxos/utils` [@richburdon]
- [ ] remove package and split into: types, async, debug, testing.
- [ ] consolidate other "factor out" TODOs.

## `@dxos/protocols` [@richburdon]
- [x] move type defs (factor out defs for feeds, streams).
- [x] resolve `TypedMessage` and halo `MessageType`.
- [ ] move script `gen-proto-defs.ts` to tools.
- [ ] move testing definitions and util functions to other package (see client-testing).
- [ ] remove required; replace camelCase with underscores.
- [ ] rename/normalize "Message" classes (e.g., `EchoEnvelope`). 
- [ ] remove deps from common (`@dxos/feedstore`)
- [ ] factor out timeframe to separate package. remove "I" prefix from typedefs.
- [ ] rename/move halo `PubKey` and `PrivKey` defs and substitutions.
- [x] move `@dxos/rpc` to `core/mesh`.
- [x] move to core.
- [x] move PublicKey to `@dxos/keys`.
- [x] remove different keytypes (e.g., PartyKey).

## `@dxos/feed-store` [@richburdon]
- [x] #1682

## `@dxos/hypercore` [@richburdon]
- [x] move hypercore basics here with TS defs.
- [ ] upgrade to v10 (classes).

## `@dxos/random-access-storage` [@richburdon]
- [x] TS defs.
- [ ] upgrade to v6 (classes).

## `@dxos/client-services` [@richburdon]
- [x] #1745
- [ ] move DataService from echo-db to client-services.
- [ ] replace "party" with "space" throughout.
- [ ] rethink service APIs.
- [ ] service factories (incl. Data/Devtools service construction).
- [ ] figure out what to do with client running in local-mode (previously we passed database by pointer).
- [ ] move echo-db error defs to new halo module.
- [ ] rename service files (e.g., party-service.ts)
- [ ] rethink ServiceContext (e.g., DataService, SpaceManager).
- [ ] ServiceContext remove public member access.
- [x] move from `@dxos/client`.
- [x] move SpaceManager to echo-db (factor out invitations).
- [x] remove `types.ts` files (anti-pattern).
