### ISSUE TITLE
Documentation and READMEs

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1625]
- [ ] prepare `dxos` repo for public access
  - [ ] READMEs in all packages follow a template (badges)
  - [ ] Contribution guide.md
  - [ ] Licenses are checked and MIT
  - [ ] unpublish from npm
  - [ ] republish as versions 0.1
  - [ ] Issue template is set up 
- [ ] set up documentation site `docs.dxos.org` and prepare it for public access
  - [ ] `Why DXOS?` motivation document
  - [ ] guide
  - [ ] #1368 
  - [ ] search
  - [ ] version selector
- [ ] Sample code
- [ ] Product Roadmap
