### ISSUE TITLE
ECHO readiness

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1629]
- [ ] https://github.com/dxos/protocols/issues/490
- [ ] https://github.com/dxos/protocols/issues/1345
- [x] ECHO refactoring (remove hints, control feeds)
- [ ] #1576 
- [x] #1300
