### ISSUE TITLE
HALO application

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1630]
Using the app, users can:

- self-identify
- recover their halo / absorb it from another device
- discover and inspect the network
- join parties (spaces)
- send simple messages to each other once in a space
- create and collaborate on a list of strings in a space.
- join HALO across multiple devices (including the CLI)

---

- [ ] Spec (TODO: link GH issue/document): app and user experience (https://www.figma.com/file/QY7QhVXKddDEOXLGVlEjBI/HALO)
- [x] https://github.com/dxos/protocols/issues/1325: Stage 1
- [x] Get Vite workspace deps working
- [ ] Vite module resolution fix (sodium-universal browser mapping)
  - [x] DXOS-only patch
  - [ ] Vite fix (https://github.com/vitejs/vite/pull/8709 / https://github.com/vitejs/vite/pull/9441)
- [x] Config plugin for rollup
- [x] Setup basic DXOS app shell/template in PWA template (https://github.com/dxos/dxos/pull/1538)
  - [x] Hook up registration flow for new profile
  - [x] Hook up registration flow for profile recovery
  - [x] Hook up sharing dialog for adding devices to a HALO
  - [x] Create basic interface for displaying HALO
  - [x] Create basic interface for adding/joining spaces
  - [x] Create basic interface for displaying space data
  - [x] Create basic interface for editing space items
  - [x] Hook up sharing dialog for granting members access to space
  - [x] Create basic interface for editing space metadata
  - [x] Make components responsive
  - [x] Update Party language to Space
- [x] PWA Research and Testing
  - [x] dxos/dxos#1641
    - Service workers can be installed without user action (https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#registering_your_worker)
    - In Chrome you can also optionally prompt end-user to install a PWA (https://web.dev/learn/pwa/installation/#prompting-for-installation)
  - [x] dxos/dxos#1640
    - "The fetch event lets us intercept every network request made by the PWA in the service worker's scope, for both same-origin and *cross-origin* requests" https://web.dev/learn/pwa/serving/#the-fetch-event
    - if you make a cross-origin request from a page, it will go through the service worker that manages the page. If there's a service worker registered for the url on the other domain, it will not go the other domain's service worker. https://github.com/w3c/ServiceWorker/issues/130#issuecomment-30652354
  - [x] Shared Worker/Client RPC
    -  webrtc is not yet supported in workers (https://github.com/w3c/webrtc-pc/issues/230, https://github.com/w3c/webappsec-csp/issues/92, https://github.com/w3c/ServiceWorker/issues/1522, https://github.com/w3c/webrtc-pc/issues/2553)
    - possible communication channels:
      - ~transferable streams (https://stackoverflow.com/questions/54766128/can-a-pwa-run-a-webrtc-connection-in-the-background)~
      - ~websocket sterams (https://chromestatus.com/feature/5189728691290112)~
      - message passing along the lines of how devtools works (https://web.dev/two-way-communication-guide/)
    - if client lives in a service worker is it possible to stream audio/video uninterrupted due to worker lifetime? No, when needing to open some sort of long standing channel between two peers the client backend would need to give the frontend the details so that it could make that connection on it's own.
  - [x] Test various limited connectivity use cases to ensure PWA template caches app appropriately
    - For the most part the app "just worked" offline using the default vite-plugin-pwa service worker. The exception to that was the dynamic config request to kube which failed when offline. Catching that failure allowed the app to work offline.
    - Other future considerations:
      - Can we cache the config request? pwa plugin has an option `additionalManifestEntries` which seems to map to the workbox precache, but emits a warning when I include the well known config path without a revision https://developer.chrome.com/docs/workbox/modules/workbox-precaching/#explanation-of-the-precache-list I think that means that without it, it will not be predictably updated. Passing in a string removes the warning but the docs say "It's strongly recommended that you use one of Workbox's build tools to generate this precache manifest. Never hardcode revision info into a "hand written" manifest, as precached URLs will not be kept up to date unless the revision info reflects the URL's contents!" These tools seem more intended for caching assets within the application, since the config request lives independent from the application I'm not sure we want to use them to cache the config request. Perhaps if we used our own service worker we could intercept and cache the results of that request based on the current version of the app, however what if kube changes config between versions? Config needs a way to become invalidated
      - Do we want the service worker to cache other media assets (e.g., images stored in ipfs)?
  - [x] Understand better and document mechanisms for PWA cache reset when necessary
    - Using default update mechanisms in the vite-plugin-pwa, once new assets have been deployed, the first reload downloads and installs the new assets and the second reload uses them within the app
  - [x] Cross-domain service workers
    - These generally seem to work fine, however stricter browser settings seem to block them (e.g., Brave shields) so that may need to be taken into account when building apps
- [ ] Add new functionality to app to scan QR codes from mobile devices to join a HALO
- [x] Publish app to well known location: `halo.dxos.org`
- [x] Login with HALO flow (https://github.com/dxos/dxos/pull/1512)
  - load identity creation/selection interface in iframe modal
  - HALO app creates device invitation and passes it back to the authenticating app to be redeemed
  - once redeemed the app is now an autonomous device within that identity

### Bugs

- [x] dxos/dxos#1641 
- [x] dxos/dxos#1640
