### ISSUE TITLE
HALO CLI/API Review

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#1632]
## HALO/Signaling Reliability (All-hands)
- [ ] API
  - [ ] Standardize invitation JSON vs QR vs URL (and base62 encoding)
    - https://github.com/dxos/protocols/blob/main/packages/demos/dx-cli/src/commands/space/invite.ts#L49
    - https://github.com/dxos/protocols/blob/main/packages/demos/dx-cli/src/commands/space/join.ts#L40
    - https://github.com/dxos/protocols/blob/main/packages/demos/kodama/src/components/invitations/Join.tsx#L32
    - https://github.com/dxos/protocols/issues/1423
  - [ ] Invitation API (catch errors, blocking calls, etc.)
  - [ ] Inviter must sleep before exit post invitation (for replication); in general waiting for events.
  - [ ] HALO recovery hangs if other peer offline.
  - [ ] Client options and Config proto (e.g., standardize storage).
  - [ ] Client init/destroy clean-up.
  - [ ] Cancel invitation/timeout
- [ ] Circles
  - [ ] Circle messaging (presence/invitations) via signaling swarm (peers subscribe to identity key)
  - [ ] Replicated profiles (indexed by identity key); added via spaces
- [ ] Functionality
  - [ ] Impl: https://github.com/dxos/protocols/pull/1412
  - [ ] Kodama device management/recovery.
  - [ ] Works on mobile (with PWA).
  - [ ] Publish dx-cli (handle different versions with legacy, config, ~/.dx folder, etc.)
  - [ ] Auto-update dx-cli
- [ ] Development
  - [ ] Logging and diagnostics (esp signaling).
  - [ ] End-to-end testing.
- [ ] Errors and reliability
  - [ ] KUBE signaling reliability (and stabilize endpoint).
  - [ ] DX-CLI Error after invitation ./testing/user-1.sh: line 28: 41630 Segmentation fault: 11  $dx space invite $KEY
  - [ ] Corrupted halo if attempt to crate party without profile (see TODOs in dx-cli scripts). Reset.
  - [ ] Standardize error handling.

## Scenarios (Spec)

- Admitting new users into a Space requires the Sender to know the identityKey of the Receiver.
- The Sender may already know the identityKey (i.e., it's already part of their Circle) or discovers it via key-exchange (over the Signaling network) using a second-factor token.

1. Invite new user.
- Inviter writes invitation to Space.
- Sends invitation token/url with secret as second factor; invitation contains partyKey, which is used for WebRTC swarm.

2. Invite known contact from Circle.
- Peers (devices) subscribe to BOTH identity (user-to-user messages) and device key (e.g., for WebRTC signaling).
- Inviter writes invitation to Space.
- Inviter sends message (via signal network) to identity key; invitation contains partyKey.
- Receiver gets invitation notification and joins WebRTM swarm using partyKey as discovery key.
- Receiver accepts invitation and authenticates.

## API

Pseudo-code for main HALO workflows.

Inspiration: 
- React Apollo GraphQL
- https://nodejs.org/api/async_hooks.html#asynchronous-context-example

```ts
// Sender
{
  // Create initial profile (abstraction by react).
  const profile = await client.createProfile();

  // Create space.
  const space = await client.createSpace();

  // Create invitation (writes invitation to feed and initiates connection.)
  // NOTE: Once the invitation is written, a different peer may accept the invitation on the sender's behalf.
  // ISSUE: Pass in callbacks (like Node example above) or have `invitation.on` methods?
  const invitation = space.createInvitation({ 
    onComplete(() => {
      log(space.getMembers());
    }),
    onError(() => {}),
    timeout: 5000 
  });

  // Send invitation (if user already in HALO Circle).
  client.halo.send(userKey, invitation.token);

  // Get invitation URL (to send out-of-band).
  copyToClipboard(invitation.url);

  // Get n-digit second factor secret.
  log(invitation.secret);
}

// Receiver
{
  // Accept invitation (initiates connection).
  const invitation = client.acceptInvitation(token, {
    // Prompt user to enter secret (may be optional).
    onConnect(() => invitation.setSecret(secret)),
    onComplete(() => {
      const space = invitation.getSpace();
      const members = space.getMembers();
      log(space.getMembers());
    }),
    timeout: 5000
  });

  // Cancel early.
  invitation.cancel();
}
```

## Demo
- https://github.com/dxos/protocols/pull/1451 (see screen casts)

## DX-CLI

Semi-automated testing.

https://user-images.githubusercontent.com/3523355/185660807-3c6f1c15-58f6-4256-a366-039ff89403e5.mov

## Kodama

https://user-images.githubusercontent.com/3523355/185662543-4be5999e-1585-410b-9b6a-4d002bf54618.mov

## PWA demo:

<img width="1728" alt="Screen Shot 2022-08-16 at 11 44 14 PM" src="https://user-images.githubusercontent.com/3523355/185030276-69d4fc36-844a-4f5f-b4be-36456944fbe1.png">

## Lexical collaboration demo:

<img width="1269" alt="Screen Shot 2022-05-08 at 7 40 24 PM" src="https://user-images.githubusercontent.com/3523355/167487933-8d0455cd-e13e-4c11-a350-553f90be2e9a.png">

## Spec
Installation:
1. `npm install -g @dxos/cli`

Kodama is an interactive experience to inspect HALO, ECHO, MESH on the terminal. It ships as part of the`dx` CLI. 

2. `dx shell` runs the interactive `kodama` shell, where developers can:
  - create or import a HALO identity
  - create, list, join spaces
  - manage authorized devices
  - add to a list of string entries in every space (later we'll make this into a chat client)

3. `dx kube install` same as the curl command available on our website, making `kube` available globally 

- [ ] open PWA and give it HALO context silently
- [ ] commands
  - [ ] `dx shell`
  - [ ] `dx version/help`
  - [ ] `dx kube install`
- [ ] Evaluate yargs vs oclif
  - [x] TS/build
  - [x] Create '@dxos/client', '@dxos/config'
  - [ ] Error handling
  - [x] Modularity/extensibility (plugins)
  - [ ] Deploy cycle (e.g., oclif pack:macos); updating
  - [ ] Inquirier/Ink integration

### Out of scope for M0
- [ ] non-interactive CLI mode for all the features above are out of scope for M0

### PRs

- https://github.com/dxos/protocols/pull/1361
