### ISSUE TITLE
Platform Operational Readiness

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1644]
### Milestone
- [x] #1634 

#### Ops
  - [x] #1706
  - [x] dxos/kube#424
  - [ ] MESH (signaling)

#### Product
  - [x] dxos/kube#505 
  - [x] #1704
  - [ ] License check (we are not using software we shouldn't, we have stock of our licenses)
  - [ ] Terms of use and privacy policies exist in repos where appropriate
  - [x] #1709

#### Dev
  - [x] #1705
  - [x] ECHO telemetry (number of spaces, number of users, size of spaces, update time series)
  - [x] #1654
