### ISSUE TITLE
Browser Developer Tool

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1646]
- [x] readme.md (installation, how to run the extension in dev mode)
- [x] make it stable 
  - [x] add IFrame managment
- [x] fix client services
  - [x] refactor DevtoolsService to class
  - [x] Fix SwarmPanel
  - [x] Fix EchoPanel
  - [x] Fix ConfigPanel 
- [ ] end to end smoke test of the browser extension
---
- [x] standalone client compatibility mode
- [ ] some api feedback written up somewhere?
- [x] Add Telemetry
- [x] Publish it

---
## Stuff to add
- [x] Identity page (json dump with all data from your profile)
   - [x] Rename Profile -> Identity
- [x] keyring page (with all keys from your keyring) 
- [x] Add console log to client to open DEVTOOLS
- [x] Remove Controls
- [ ] SwarmPanel refactor
- [x] Humanized names
- [ ] Timeframe fix

---
Ideas
- [ ] Add ECHO editor to fix database on the go
- [ ] Add invitations panel
- [ ] Add signal server output

---
Icebox
- [ ] UI bump (use our new shiny ui shit)
---
_notes from the talk with @richburdon_ 
## Milestones

- [x] strip down devtools sidebar to limit to things that are working
- [x] create switch (boolean variable) to toggle local/remote client mode
- [x] create spaces
- [x] create items
- [x] create/join invitations

There are 3 modes devtools should be able to run in.
![Image](https://user-images.githubusercontent.com/36420699/198077110-ed78878f-e844-4183-929f-3b372d5228fc.png)
