### ISSUE TITLE
rewrite feed-store package.

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#1682]
## PRs
- [x] https://github.com/dxos/dxos/pull/1611
  - Added shims for all hypercore related packages
  - Comprehensive unit tests for major hypercore functionality 
  - Low-level hypercore tests: https://github.com/dxos/dxos/pull/1670/files#diff-60f62c40c1ef6e38ee331e993ee7c7598f710cda5d6df98ea98c1b0c41e14309 (once I have all of the feed-store integrated and landed, this will help me test and migrate to hypercore 10; i'm also planning to do the same for hypercore-protocol)
- [x] https://github.com/dxos/dxos/pull/1670
  - Hypercore shims: https://github.com/dxos/dxos/pull/1670/files#diff-4ae13396f98fa66404c51d767e5502b4f7a8713c8fc509ee8a4102310213fe84
  - Hypercores are now generic -- with the type matching the codec; Example: https://github.com/dxos/dxos/pull/1670/files#diff-00b10ecc53a4d5b5b9b2ac7d0254d8f2700dc6f4ef6d94625f25c9feed20c43e
  - FeedSetIterator brings everything together: https://github.com/dxos/dxos/pull/1670/files#diff-6f79fce3ed12a2908201bab40bb301d82e0bb0ec6080ce57990b187b4b76b653 
  - Note also the TestBuilder pattern! This really worked for me -- I was able to incrementally add things to it as required (e.g., value encoding) 
  - I learned a bunch about hypercore, incl. reliability (https://github.com/dxos/dxos/pull/1670/files#diff-ba6e76682f7c33275ed55355323cd6d6a7d9c36f5a61d2c0f3d4c1a34c4ec940) and the need to wrap their streams (with readable-streams) so that closing feeds happens cleanly

## Stage 1
- [x] hypercore shims
- [x] complete set of `@dxos/hypercore` unit tests
- [x] feed queue with peek/pop
- [x] feed AsyncIterator (with reliable open/close, pause/resume)
- [x] remove hypercore feed accessor from FeedDescriptor (debug only). And normalize use of descriptor/wrapper/feed.
- [x] reconcile custom types (e.g., IFeedGenericBlock) with custom hypercore ts defs (hypercore-types.ts)
- [x] rewrite without deps on `@dxos/protocols`.
- [x] replace `@dxos/protocol-plugin-replicator` use of direct hypercore objects with FeedDescriptor wrappers.
- [x] move FeedWriter, etc. from `dxos/protocols`.

## Stage 2
- [x] integrate with echo-db
- [ ] integrate with protocol replicator
- [ ] package level Error class
- [x] test timeframe based selector
- [x] trigger feed-set-iterator on new feed or message
- [ ] test adding feeds on-the-fly

## Stage 3
- [ ] performance benchmark
