### ISSUE TITLE
`dx` CLI telemetry

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1704]
We will have to support the following business questions with our telemetry:
- are users using the `dx` CLI in meaningful ways? how many unique, active users? what does growth and churn look like?
- what features of dx cli do users use the most?
- what features are used the least?
- what kind of hardware does the cli run on?
- how often do people deploy things with the cli?
- how often do people create apps with the cli?
- how many cli installations run with telemetry turned off?

---
## Todo:
- [x] pick a telemetry api (segment)
- [ ] events
  - [ ] cli startup when telemetry is OFF
    - [ ] isOptedOutOfTelemetry: true
    - [ ] installationId
  - [ ] cli command invocation completed
    - [ ] command invoked (without arguments or any freeform user input)
    - [ ] end to end service time / duration of command
  - [ ] publish command completed
    - [ ] bundle size published
  - [ ] all events
    - [ ] installation id (ideally same as the one used by kube on the same machine)
    - [ ] os platform and version
    - [ ] global node version
    - [ ] local timezone offset
    - [ ] general geographic locale of public ip address?
    - [ ] is this a CI machine?
- [ ] errors and their stack traces collected (stack traces should be opt in only) (sentry)
- [ ] ability to disable telemetry via configuration
- [ ] `isInternalUser` boolean to be attached to telemetry events if the installation (~/.some-config-file) is marked as internal user. Internal employees will mark this manually or with an internal tool.
- [ ] textual confirmation of internal user during startup
