### ISSUE TITLE
HALO app telemetry

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1705]
see this issue to reuse the same framework decisions:
- [x] #1704 (segment)

The following business questions will need to be supported by our telemetry:
- are users using HALO app in meaningful ways? how many active, unique users? what does growth and churn look like?
- how are user using the app the most?
- the least?
- how much traffic is the halo app handling, which routes?
- what kinds of errors are thrown under what conditions and how often?
- what kinds of user agents are used when accessing halo?
- how much disk is our indexdb using?

--- 
## Todo:
- [ ] events
  - [ ] page is ready / rendered
    - [ ] how long did it take to render
  - [ ] router navigation events
    - [ ] which route
  - [x] clicks/activations of hrefs and buttons
    - [ ] which #id was activated
  - [x] page focus
    - [ ] time spent in the background
  - [x] page blur
    - [x] time spent active on the page
  - [ ] page closing / navigating away from halo
    - [ ] time spent on page in this session?
  - [ ] all events
    - [ ] installation id (localstorage)
    - [ ] user agent and version
    - [ ] total current indexdb storage size
    - [ ] hash of identity id
- [ ] allow users to opt out of sending telemetry (ideally same flag machine-wide for cli and kube, this incl all telemetry including errors and events under one switch)
- [ ] errors and their stack traces (stack traces should be opt in only) (sentry)
- [ ]  `isInternalUser` boolean to be attached to telemetry events if the installation localstorage is marked as internal user. Internal employees will mark this manually or with an internal tool (bookmarklet).
- [x] #1813
