### ISSUE TITLE
Todo list feedback

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#1893]
# todo list feedback
- [x] no need for re-ordering UI for now
- [x] no need for description field for now
- [ ] make change events more granular.

Each list item will be a separate item in the database rather than a property on the list. we need events that are granular to the specific change to avoid spamming mutations to the db or doing diffs in the container component.
