### ISSUE TITLE
App feedback

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#1932]
## Halo
- [ ] Generally more whitespace around inputs (too close to border)
- [ ] Replace "authed" with "authorized"
- [ ] Remove "why not" and "try" from `Why not try creating one, or joining one in an app?`. "Click Apps to launch an application."
- [ ] In the Apps panel hardcode links to Tasks and Composer
- [ ] When switching between Apps and Spaces the title jiggles because there's no button for Spaces
- [ ] When showing keys (e.g., Devices) call `PublicKey.truncate` or `humanize` rather than display long key (e.g., Devices tab)
- [ ] Display seed phrase on identity creation.
- [ ] Enable cancel button on Auth device dialog.
- [ ] Clicking on "Show QR" button in invitations row actually closes the QR (move hover only)?
- [ ] In general the button borders are distracting. Show only in accessible mode?
- [ ] During identity creation, don't allow empty string.
- [ ] Display names are not editable after the fact (currently) so disable the input in the manage identity dialog
- [ ] In general I don't love the full width buttons. Prefer fixed size/aspect buttons in a horizontal button bar. (e.g., in manage identity dialog see "Disable" and "Reset"). It's tempting to go full wide, but there will generally be 2-3 buttons.
- [ ] IMO headings look better with font weight 100.
- [ ] Help button in lock screen should link to docs.
- [ ] Display version, build#, etc. at bottom of page.
