### ISSUE TITLE
Return full file paths to the log preprocessor

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#2177]
Log preprocessor now emits only the filename of the source file, without the full path from the root of the monorepo:
`example.ts` instead of desired `packages/example/src/example.ts`.

We cannot set the full path in `filename` prop passed to SWC because that breaks source maps.

Add a `pathPrefix` config option to the plugin config that will be prepended to the filename. Esbuild should set the prefix so that logger emits full file paths.

### Subtasks

- [ ] Readme links to docs on writing SWC plugins in rust https://github.com/dxos/dxos/tree/main/tools/swc-log-plugin
- [ ] SWC plugins can take custom config in the form of JSON.
- [ ] Config can be accessed from the `_metadata` param here https://github.com/dxos/dxos/blob/main/tools/swc-log-plugin/src/lib.rs#L192
- [ ] Set the prefix as a filed on the transformer struct
- [ ] Prefix should be optional so that the tests don't require it
- [ ] If you need to parse json use `serde-json` crate with the `#[derive(Deserialze)]` syntax
- [ ] Building rust sources is not included in the NX pipeline, don't forget to build (instructions in readme) and commit the WASM module to git.
- [ ] Configure esbuild executor to provide the correct path prefix - the resulting path should be a full path to the source file from the repo root

### Extra tasks

- [ ] Every log call gets its own string literal for the filename yet they are the same, this can be optimized by emitting a const with a non-colliding name like: `const __dxlogFilename = 'packages/..../src/example.ts'` at the top of every module and then using them instead of string literals.
