### ISSUE TITLE
ECHO DB2 Spec

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#2178]
## Kai (Use case)

- [x] Invitation flow
  - [x] QR code
- [x] Mobile app (PWA)
- [x] Reset storage
- [x] Playright
- [x] Devtools (show feeds, timeframe)

## Features for the new proxy api

- [x] Deletion (and references)
- [x] TextModel & custom models
- [ ] Parent-child + strong refs
- [ ] Schema validation
- [ ] Cross-space references
- [x] #2226
  - [x] Splice
- [x] Inlined subobjects
- [x] Query/subscription API

## Database architecture and stability

- [x] #2227
- [x] Extract the current database together with `echo-db2` into a separate package
  - [x] Remove the legacy api (the `Database` class) in favor of new `EchoDatabase`
- [x] Remove the need to run model frontend at the shared worker
- [x] Remove links
- [x] Move object metadata props (`parent`, `deleted` etc., into StateManager`)
- [x] Consider moving state manager out of model-factory
- [x] #2208
- [x] #2195
- [x] `google.protobuf.Any` for mutation embedding
- [x] Use `plate` for codegen

## Epochs / Snapshots

- [x] Defer initial data presentation on startup until last saved timeframe is reached
- [x] Store snapshot by CID
- [x] API to reset the database to a particular snapshot
- [x] Option to start (and restart) the data pipeline from a particular timeframe
- [x] Use snapshots locally to optimize the startup time: each agents creates it's own snapshot periodically, and loads from it on next startup
- [x] Protocol extension for snapshot exchange (CID based, similar to BitTorrent)
- [ ] Exchange the snapshot on invitaions
- [ ] Credential to allow epoch creation
  - [ ] Agents that have "create epochs" permission, create snapshots and write epoch messages to control feed referencing that snapshot
  - [ ] Other agents scan the control feed for epoch messages, and start the data pipeline from the last epoch

## Startup synchronization

- [x] Record the processed timeframe for the data pipeline in the metadata and on the next load wait until that timeframe is reached.
- [ ] During invitations shared the current timeframe so that the Guest can wait till it's synced to that timeframe.
- [x] Expose some way in the API to indicate spaces that are currently syncing and not ready (cc @zhenyasav what do you think?).
- [x] Implement same "last timeframe" semantics for the control feed so that we index all control messages before starting the data pipeline.

## Bots

- [ ] Life cycle management (execution and swarm membership) for bot processes belonging to Space
- [ ] Initiate epoch generation

## Time travel (and undo)

- [ ] API to Generate a snapshot for a state at a given timeframe in the past
- [ ] API to get a frozen database state at a given timeframe in the past
- [ ] Undo/redo design

## Multi-device support

- [x] https://github.com/dxos/dxos/pull/2157
- [x] Add "greeter" extension to space protocol that allows new agents to admit their feeds
- [x] Record member credentials for the joined & created spaces in the HALO spaces
- [x] Devices automatically join spaces based on credentials from HALO
