### ISSUE TITLE
Mykola's TODO

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#2255]
# Mykola's public TODOs list

- [ ] `project.json` templating
- [x] https://github.com/dxos/dxos/issues/2402
- [ ] Refactor ObjectModel builder
- [x] https://github.com/dxos/dxos/issues/2287
- [ ] add RPC stack calls to Devtools
- [x] https://github.com/dxos/dxos/issues/2448
- [ ] https://github.com/dxos/dxos/issues/2449
- [ ] implement comments from https://github.com/dxos/dxos/pull/2454
- [x] https://github.com/dxos/dxos/issues/2445
- [ ] `ws-rpc-peer` https://github.com/dxos/dxos/pull/2522/files#r1120422148

## DEVTOOLS ideas
- [ ] Dynamicly load Iframe from Kube in Devtools
- [ ] https://github.com/dxos/dxos/pull/2179
- [ ] intractable json viewer https://www.npmjs.com/package/react-editable-json-tree
  - [ ] render reference and array https://github.com/dxos/protocols/blob/3bb482e8fc8fe50d8fd6577e62e140bc1cc5162d/packages/deprecated/react-components-deprecated/src/JsonTree/JsonTreeView.tsx#L207

## CLI
- [ ] CLI

--- 
### DONE
- [x] https://github.com/dxos/dxos/issues/2618
- [x] space.properties undefined bug 
- [x] https://github.com/dxos/dxos/issues/2378 (type props)
- [x] Make devtools even with some failures in Client Services
- [x] space export does not work
- [x] in the Note frame, when you move the position of a Note, the data seems to be replicated, but the subscription isn't updated here: https://github.com/dxos/dxos/blob/main/packages/experimental/kai/src/frames/Note/NoteFrame.tsx#L86
- [x] Post extension in google store
- [x] Fix WebRTC 'go offline' test
- [x] Fix Presence in Kai
- [x] refactor Devtools
- [x] Autoupdate extension in google store
  - [x] fix extension bundle and rename back `bundle-skipped` -> `bundle`
- [x] network-manager skipped and flaky tests
- [x] https://github.com/dxos/dxos/issues/2406
- [x] rename object-model -> document-model
- [x] https://github.com/dxos/dxos/issues/2357
- [x] fix Kai on plex branch
- [x] Echo root object with space title
- [x] delete type from document-model
- [x] https://github.com/dxos/dxos/issues/2489
- [x] https://github.com/dxos/dxos/issues/2371
- [x] https://github.com/dxos/dxos/issues/2450
- [x] https://github.com/dxos/dxos/issues/2520
