### ISSUE TITLE
Storage Versioning

### ISSUE THREAD

**Issue by rzadp** [dxos/dxos#227]
Do after #268

Detect storage version that the user has and compare to storage version that the ECHO supports.
If mismatch, try to "migrate" i.e. read and re-write with updated version, or allow the user to reset storage.

## Tasks

- [ ] Define new storage for version https://github.com/dxos/protocols/blob/main/packages/sdk/client/src/client.ts#L406
- [ ] Refer to SnapshotStorage in ECHO for example and define VersionStorage class (`read(): string`, `write(version: string)` methods)
- [ ] Define the API on the Client

## Pseudocode of how it would be used from appkit or teamwork

```
const client = new Client()

client.storageVersion // comes from disk

client.clientVersion // clients own metadata from pkg json

if(client.storageVersion != client.clientVersion) {
  // Display popup
}


client.initialize()
```
