### ISSUE TITLE
Apps usability features  

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2273]
todo lists (kai + todo-app)
- [x] keyboard navigation through todo items (up, down, enter creates a new item)
- [x] have the scroll position stick to the bottom when creating/editing the last item in a todo list
- [ ] simplify focus outline to just an underline (or similar minimal treatment) while within a todo list surface (to be more like a page of todos than a list item or input box)

sidebar (to allow for context awareness / preservation when navigating from the sidebar on mobile)
- [x] allow the sidebar to overlap the main content area when animating in on mobile (without pushing it away, so you can tell where you are if navigating)
- [x] do not blur the content area
- [x] translucent effect + blur / frosted effect in the sidebar backdrop for text readability in sidebar
- [x] put a close button in the top, same height as L0 topbar

Other items
- [ ] Try to improve width-oriented experience in the table component
- [ ] Dragging should not cause tasks to jump
- [x] `composer`’s wrapping `div` should be able to be styled
- [ ] ~the keyboard popping open covers the new task input rather than pushing it up~

**Comment by thure** [comment]
> the keyboard popping open covers the new task input rather than pushing it up

I've investigated the matter more thoroughly, and it looks like this is a very non-trivial problem. I also can’t find an actively maintained solution in the ecosystem.

This is the most succinct & thorough summary of the situation I could find, and its facts are still relevant now: https://www.bram.us/2021/09/13/prevent-items-from-being-hidden-underneath-the-virtual-keyboard-by-means-of-the-virtualkeyboard-api/

A robust solution to the problem would apply `sticky block-end-0` (prefixed by `focus-within:` as needed) _except_ on iOS Safari which would need to use or re-implement functionality from a project like [`react-sticky`](https://github.com/captivationsoftware/react-sticky) but use [the `VisualViewport` API](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport) to determine the correct position.
