### ISSUE TITLE
23Q1

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2327]
# Objectives:
1. **Eat our own dogfood**
Develop an application for managing shared knowledge with DXOS and use it internally every day
    - shared lists of user stories, requirements, OKRs, ... etc
    - customer relationship records
    - recruiting records

2. **Engage developers**
Establish a few external developers who experiment with DXOS to build their app.

# Epics
- [ ] 23Q1 Framework
  - [ ] Land Experimental APIs
  - [x] #1345 
  - [x] #1346 
  - [ ] Epochs #490 
  - [ ] Automated E2E and stress tests use gravity
  - [ ] Invitations (Space, Devices) end-to-end
- [ ] 23Q1 Platform
  - [ ] Config consolidation
  - [ ] KUBE exposes applications to the web via tunneling
  - [ ] KUBE supports a HALO security model for KUBE admin functions
  - [ ] Firewalls
  - [ ] Docs brownouts
  - [ ] Set up product telemetry dashboards
  - [ ] KUBE ergonomics
- [ ] 23Q1 Apps
  - [ ] Migrate samples and docs to experimental API
  - [ ] Card-stack component
  - [ ] Mobile support
  - [ ] Shell components
  - [ ] Merge tasks-app and composer
  - [ ] Braneframe 0.1
  - [ ] KUBE Console
  - [ ] Inspector
  - [ ] DX CLI cleanup
