### ISSUE TITLE
Devtools clean-up

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#2331]
- [ ] Remove deprecated material panels (upgrade JSON tree view, etc.)
  - [ ] JSON view
  - [ ] Table: Scrolling, Filter
  - [ ] Selector
- [ ] Cleanup
  - [ ] Reconcile sandbox/testbench?
  - [x] Refactor custom start up logic (e.g., creating client) into hooks.
  - [x] Factor out common code for App.tsx and Devtools.tsx
  - [ ] All startup code (for different entrypoints) should be within a `main` function
  - [x] Standardize pattern: `html => main.tsx => App.tsx => <Routes />`
- [x] Restructure containers/panels
- [x] Hash router

## PRs

https://github.com/dxos/dxos/pull/2330

## Widgets

- https://www.npmjs.com/package/react-sparklines
- https://recharts.org/en-US/examples/PercentAreaChart
- https://codesandbox.io/s/n97xpmr464
- https://www.npmjs.com/package/react-apexcharts
