### ISSUE TITLE
CLI enhancements

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2354]
- [ ] add `logs` command to show logs from kube (design needed)
- [ ] error verbosity and help links
- [ ] clean up halo commands
- [ ] fix or remove kodama
