### ISSUE TITLE
API Feedback

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2378]
## Props
- [x] db.add/remove (delete/undelete?)
- [x] Using symbols as keys to access stuff is awkward (e.g. deleted, id field etc)
```
id
__typename
__deleted
```
- [x] `db.properties`

## Queries
- [x] `db.query` should not return deleted items unless specified in an options argument
- [x] destructuing in queries `const { objects } = space.db.query(Task.filter())`
- [x] warn when accessing field reads (e.g. `task.title`) without a `withReactor` (search) @dmaretskyi 
- [ ] consider ergonomics of `db.query(Task.filter( { completed: true } ))` and how to select for deleted objects
```ts
db.query(Task, { deleted: true })
db.query(Task.filter({ completed: true }))
db.query(Task.filter(task => task.completed))
```
- [ ] Later: Timeframe based predicates?

## Types
- [x] Codegen basic and object types as FooProps
- [ ] nested proto defs
```typescript
type Address = {};
type ContactProps = { name: string, address: Address }
class Contact extends Document<ContactProps> {
  declare name: string;
  declare address: Address;
}
namespace Contact {
   type Nested = { ... }   
   class Nested { ... } // not allowed
}
```
- [x] schema types: `schema.types`
- [ ] `typegen` props/config file. (stretch)
  - [ ] Later consider global schema namespace/queries/dynamic registration`client.echo.register(schema)` move to config? (stretch)
```
// dx.yml
schema:
  - schema.proto
```
```ts
function registerSchema(client) {
   schema.add(Contact)
}
```
- [x] use plate https://github.com/dxos/dxos/pull/2541
- [ ] schema validation

## Mutations
- [x] `foo.list = [1, 2, 3]`
- [x] `foo.doc = "abc"` (wontfix)
- [x] `const text = foo.doc.text` @dmaretskyi 
- [x] auto construct text document
- [x] Document vs DocumentBase (search)
  - [x] can't access random fields on `DocumentBase` unless it's typed `any` (use Document instead?)
- [x] consider implementing synchronous updates to objects to improve react integration

Misc
- [x] sync space credentials across HALO
- [x] pick an observable pattern that is compatible with `useSyncExternalStore` [@wittjosiah]
- [ ] don't require `new Config` to instantiate a `Client` [@wittjosiah]
  - [ ] don't nest config inside a `config` property to the `Client` constructor

**Comment by zhenyasav** [comment]
https://reactjs.org/docs/react-api.html#reactchildren (for passing custom props to opaque children)

**Comment by wittjosiah** [comment]
> https://reactjs.org/docs/react-api.html#reactchildren (for passing custom props to opaque children)

@zhenyasav the updated react docs warn against using this and suggest what we already have as an alternative https://beta.reactjs.org/reference/react/Children#calling-a-render-prop-to-customize-rendering thoughts?

**Comment by richburdon** [comment]
> Recommend top level conventions:
> 
> * `_id`
> * `__typename`
> * `__deleted`

can you show prior art? `_` to me means private. e.g., i've seen it (we used to have) __typename in our serialized JSON for protos (taken from graphql) but the meaning there was "none of your business". I personally don't get the dislike of symbols. Esp. since these aren't often used. Slightly next in line would be global accessor functions (e.g., `type(item)`).
And then possible just exposing `id` but I think that would be intrusive and error prone -- i.e., we'd have to put a type check in our proto/gql parser and people would hit that often.

**Comment by zhenyasav** [comment]
`foo.id`
`foo.__typename`
`foo.__deleted`

**Comment by zhenyasav** [comment]
```ts
pojo.__id;
pojo.__typename;
pojo.__deleted;
```

**Comment by dmaretskyi** [comment]
- [ ] data getter in queries `const { data } = space.db.query(Task.filter())`, `data : Task[]`

**Comment by zhenyasav** [comment]
We think it's cool to do `space.query(new Task({ completed: true }))` or `space.query(Task({ completed: true }))`

**Comment by dmaretskyi** [comment]
- [ ] `message TextObject` in protobuf should be importable or well-known.

**Comment by dmaretskyi** [comment]
- [ ] Ensure our proto options are defined.

**Comment by dmaretskyi** [comment]
implicit casting of `string` to TextObject makes it difficult to generate the type declarations:
https://www.typescriptlang.org/play?ts=4.9.5#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwCg4S4BzYeAE2DQSgEswYGIA7ACgEoAuONGIzZkCcKJQCuUNnDYSkSOOiVsAngF9ipNJTg06jZq04A3FEgnA+cgLYAjYFDgAffoIbCuozeqA

**Comment by richburdon** [comment]
From KAI:

- [ ] system primitive types: e.g., Timestamp
- [ ] system types: e.g., ExternalKey
- [ ] object metadata (e.g., created, modified)
- [ ] allow direct assignment of `undefined` as value (e.g., in constructor)
- [ ] `id` should be allowed as a key for non-objects.
