### ISSUE TITLE
Protocols priorities

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#2402]
Each section prioritiezed

# SDK/Framework

- [x] Promote `experimatal.db` to main API
- [x] EchoSchema object (exposed by API)
- [x] Multi-device spaces
- [ ] TextObject initial setText and sync
- [x] Correct namespace for proto compiler sub-message types
- [ ] Import dxos.keys, google.timestamp into kai/schema.proto
- [ ] Setters
  - [ ] Set value to undefined to remove
  - [ ] Set complex value (`foo = { bar: 100 }`)
- [ ] Initial sync fail (e.g., only partially display items that have actually synced)
- [ ] Initial sync fail with docs
- [x] https://github.com/dxos/dxos/issues/2378
- [ ] https://github.com/dxos/dxos/issues/2444

# Infrastructure

- [x] Data service
- [x] Clean-up other services (deprecate old proto defs)
- [ ] Re-entrant Client (and services)
- [x] Epochs
- [ ] Syncbot (basic bot service container/infrastructure)

## Tools

- [x] Devtools support for MESH (esp. swarm, signaling)
- [x] Devtools support for feeds per space
- [x] Code splitting for kai (see chess.js)
  - https://github.com/dxos/dxos/pull/2393/files#diff-dad849bf8551d1b490c4660fd329a80ae7099fcdba3bd4623b6ac35f73974ad9 
  - [x]  Factor out faker hook

## R&D

- [x] Lazy imports for dynamic modules (frames, bots)
