### ISSUE TITLE
Q1 Eng Milestones

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2430]
> TODO(burdon): Convert to spec w/ links to docs.

## 1. API / Protocols [@dmaretskyi]

> Basic stability (prep for epochs)

- [ ] Remove/upgrade services and deprecated protobufs
  - [x] Life cycle: System, Halo, Space, Invitations
  - [x] Data service
  - [x] invitation storybooks in CI w/ monitoring
  - [ ] Client idempotence
- [x] Sync space credentials across HALO
- [ ] Complete transition to new APIs
  - [x] OrderedSet, TextObject, `add`/`delete`
  - [ ] Examples, docs
 - [ ] Stability
   - [ ] Refactor text-model to stabilize it
   - [ ] Document internal structure of text-model documents (xml vs string)
   - [ ] Text-model interaction with Composer (and Monaco potentially)
   - [ ] #2550

## 2. Kai [@wittjosiah] 

> Prep for external presentations and Dogfood

- [x] Shell panels w/ invitation timeout/retries
- [x] Dev/prod (remote) mode
- [x] Prod/release process for Kai
  - [x] Manual test scripts for staging 
- [ ] Stretch: Demo video

## 3. Tools / Dev experience [@zhenyasav]

> Prep for self-service development (Discord)

- [ ] Prod/release process for Devtools + monitoring
- [ ] Dev reset experience
- [ ] CLI can join the Browser and vice versa (device invitations)
- [ ] Correlated KUBE logging with Devtools logging

## 4. KUBE / ops [@egorgripasov]

> We can see and diagnose failures in production

- [ ] CLI/credentials
- [ ] Basic dashboard and ops wiki (kibana/supabase)
- [ ] KUBE logs
- [ ] Kai prod logs: launch, invitation flows, errors (e.g., able to correlate invitations to KUBE/signaling logs)
- [ ] Diagnose LTE connectivity, TURN/ICE verification (disable)
- [ ] `dxos.network` configured for third-party publishing

## Out of scope

- [ ] KUBE/CLI credentials https://github.com/dxos/kube/issues/698
- [ ] HALO credentials / ownership / security
- [ ] Import/export Kai demo to IPFS
- [ ] Bots Docker container
