### ISSUE TITLE
Feedback (Rich)

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2444]
UI / UX:
- [x] #2446
- [x] #2447

Client / SDK
- [ ] if we use an http signaling url the client needs to throw friendly errors
- [ ] socket errors from client when using `wss` with localhost signaling
- [ ] creating an invitation with failing signaling server should not be allowed (invite button disabled when signaling isnt there)
- [x] #2676

Kube
- [ ] https://github.com/dxos/kube/issues/696

Devtools
- [x] #2450
- [ ] #2449
- [ ] #2448

Docs and samples
- [ ] sample code: ensure comments end with periods
- [ ] newline at the end of files in templates? (garbage in the buffer at the end of files produced by plate? `%` in package.json)
- [x] xcrun on mac missing (xcode-select --install)
- [ ] peer deps missing on the npm install of dx cli and npm install of our apps
- [ ] center the "your code here" thing in the middle of bare-template

DX CLI
- [ ] #2445

**Comment by zhenyasav** [comment]
we need to discuss the right strategy for sending errors from client backends to the frontend
