### ISSUE TITLE
ECHO Features/Bugs Triage

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#2721]
## Bugs
- [ ] Literal (e.g., string) arrays aren't coerced properly (currently outputs array of objects): [EchoArray being passed into defaultsDeep]
  - https://github.com/dxos/dxos/pull/2720/files#diff-5c777c44437595d38482c7170c0d87a8ffad7cec62fded0d215fd2b1718c5c32R97
- [ ] Recursion bug if component callback updated when `useQuery` results are updated (sort in filter)[#2938]  (https://github.com/dxos/dxos/issues/2938)
  - https://github.com/dxos/dxos/pull/2730/files#diff-5538d97b0402de3b89bdb1927ae884a94a94fb38d4072c45ed2b20753c1bafbdR165
  - This motivates moving the filter into useQuery otherwise the filtered result (e.g., after filter/sort) will always be a modified list, which would break `useEffect` dependencies.

## Priorities (prioritized)
- [x] useQuery filters.
  - https://github.com/dxos/dxos/blob/162fd84d18523945daa8b06b62ee9c66a80e3309/packages/experimental/kai/src/containers/SearchPanel/SearchPanel.tsx#L174
- [ ] Push `observable` further up the stack? Alt. decouple from ECHO via generic ObservableProvider (see TaskList).
- [ ] Support multiple schema files (update echo-typegen tool)
- [ ] System `meta` created/updated property (Both Timeframe AND ISO Timestamp)
- [x] Debouce query subscriptions
  - https://github.com/dxos/dxos/pull/2720/files#diff-5c777c44437595d38482c7170c0d87a8ffad7cec62fded0d215fd2b1718c5c32R41 [wontfix]
- [x] Trigger subscription callback immediately
  - Update ALL implementations to remove the additional call 
- [x] Implement enum
  - https://github.com/dxos/dxos/pull/2720/files#diff-6c3fa25f2ffed01f9aa422d85b32495fb9aaea3257703691e2b4225ac63fc323R288
- [x] Date type (ISO handling)? [WILL NOT FIX]
- [ ] Define `dxos.schema` (`dxos/schema.proto`) for tools.
