### ISSUE TITLE
QA 03/28

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2849]
- [ ] kai todo list frame does not create todos
- [ ] kai todo section in a stack does not re-render reactively
- [ ] #2850
- [ ] composer warning triangle on mobile and fails to load
- [ ] composer on desktop cannot focus empty editor if document was created on another peer
- [ ] composer navigating documents rapidly fails to render the editor sometimes
