### ISSUE TITLE
Factor out kai frames.

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#2937]
## Phase 1
- [ ] https://github.com/dxos/dxos/pull/2940
- [x] kai-frames package
- [x] Rename framebox -> kai-sandbox (TODO: @dmaretskyi)
- [x] Remove frame dependency on AppRouter
- [x] useFrameContext hook (replace useAppRouter, useAppReducer)
- [x] useFrameRegistryContext
- [ ] Frame events (e.g., router, fullscreen)

## Phase 2
- [ ] Sidebar storybook
- [ ] Frame storybooks
- [ ] Move "active" frames to registry (represents "loaded" frames)
- [ ] Frame/object binding (load frames on use)
- [ ] Reconcile appstate/nav/shell
- [ ] Mosaic components (esp. Cards, EditableObjectList)

## Phase 3
- [ ] Move BotManager panel to console
- [ ] Auto-trigger bots

## Issues
- https://github.com/dxos/dxos/issues/2968

## Next
- [ ] Factor out bot client (and bot registry)
- [ ] Kai app template
- [ ] Search object meta
- [ ] DMG frame registry
- [ ] Frame containers (e.g., sidebar, chat frame)
- [ ] Split kai-frames from frame registry (move to react-metagraph)
