### ISSUE TITLE
QA 04/06

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2966]
- [ ] device join flows don't work from halo on desktop to halo on mobile chrome and safari on ios
- [ ] kai doesn't load on mobile chrome but does on mobile safari
- [ ] kai visually broken (viewport/scrollability) on mobile safari
