### ISSUE TITLE
Kube refactor

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#3075]
### Unify Loggin
  - [ ] Make sure all services have the same logging pattern
  - [ ] Figure out slashes or semicolons 

### Naming review
- [ ] Review the difference between names `cmds`/`commands` (should we rename it)

### Testing
- [ ] Write unit tests 
- [ ] General bot service testing

### Clean up endpoints
- [ ] Do not use the `.well-known` endpoint for something else than metadata 
- [ ] Add we know that tells you what endpoint exists
- [ ] Figure what ports we are using (9002 should be gone, and general aim is 7100-7400 see bot-lab)
- [ ] endpoint router, service should not know about endpoints, permissions live inside that router

### Review services
- [ ] Move tunneling to another service from the app server
- [ ] Add kube doctor (delete `kube signal check`, check should live somewhere else)

#### Random
```yaml
  services:
    ipfs:
      server: "http://kube.dxos.org:5001/"
```
 can we delete the slash in the config?

--- 
## The end goals
-  general kube stability
- engagement of the team in kube repo
- kube console auth

**Comment by mykola-vrmchk** [comment]
@egor @zhenyasav
