### ISSUE TITLE
Restructure Kai (modules)

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3117]
https://github.com/dxos/dxos/pull/3115

- [ ] Split Sidebar
- [ ] Intents (decouple App/frames)
- [ ] Surfaces experiment
- [ ] Support labs development by external devs
- [ ] CLI app template (docs, demo video)
