### ISSUE TITLE
ECHO Improvements

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#3158]
## API

- [x] setting value to empty object does nothing, this should be documented
- [ ] when setting fields in nested objects the objects should to automatically instantiated (wontfix)
- [ ] when pushing to an array the array should be automatically instantiated? (wontfix)
- [ ] add `meta` field at the system-level (fridge)

## Devtools

- [x] text object shows up as `Unknown type` in items panel
- [x] text object text is not truncated in the list view
- [x] `[object TypedObject]` in list view could be formatted better or moved into side panel
![image](https://github.com/dxos/dxos/assets/4529818/4c922822-c7a2-4be9-9daf-4064957ea515)

**Comment by dmaretskyi** [comment]
waiting for @mykola-vrmchk to publish new version of devtools
