### ISSUE TITLE
☂️ CLI umbrella issue

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#3201]
## Daemon

- [x] https://github.com/dxos/dxos/pull/3177
- [x] Config loading & multi-profile for daemon
- [x] Hook up existing CLI commands to use the daemon https://github.com/dxos/dxos/pull/3241
- [x] Override daemon location using an env variable. https://github.com/dxos/dxos/issues/3186

## CLI -> App integration

- [x] `dx app open` command
- [x] Ability to open multiple browser profiles with one command?

## Functions

- [x] Ability to run functions manually (ts-node/nodemon) that then connect to CLI daemon
- [ ] Function API: runtime vs static spec, how do functions define triggers
- [x] Function local dev mode?
- [ ] Function deployment to KUBE?

**Comment by mykola-vrmchk** [comment]
```
