### ISSUE TITLE
Smart Calendar

### ISSUE THREAD

**Issue by Dekempsy4** [dxos/dxos#3206]
## TODO
Learning phase: create a simple application to understand dxos' backend stack better. 
- [x] Setup a blog to document and share project progress
- [ ]  Re-create dxos' tasks application following the guided documentation in a separate repository
- [ ] Register a domain name
- [ ] Host the todo application using Vercel under the registered domain
- [ ] Begin work on the smart calendar

## Ideas
- Cleaning calendar (removing unnecessary or duplicate elements)
- Dynamic calendar organization
- AI integration
- Email/Messaging integration
- How will the calendar data be populated?
    - Manual data entry by the user
    - Calendar integrates with existing calendar apps
    - Automatic event creation/suggestion based on emails

**Comment by Dekempsy4** [comment]
I've started the blog. It isn't published quite yet as there isn't much content, but it is still viewable through this link ( https://medium.com/p/2557dd305caf ). I will update the blog regularly and add pictures and such.

**Comment by jessmartin** [comment]
Closing due to inactivity.
