### ISSUE TITLE
[composer-app] Stack

### ISSUE THREAD

**Issue by thure** [dxos/dxos#3255]
Subtasks:

- [x] Refactor `[data, role]` tuples to `{ data, role }` props on `Surface` to pass to the component it renders.
- [x] _(Wait for Josiah to finish ListView increment)_
- [x] Finish Composer parity (mostly by adjusting the sidebar)
- [x] Delete old Composer
- [ ] Stack support
  - [x] Refactor File I/O and Github I/O into distinct plugins
  - [ ] _(Wait for Josiah to finish final graph increment)_
  - [x] Add Stack plugin
  - [ ] Change `…` menu to a toolbar (?)
  - [ ] Extend File & Github plugins to support Stacks
- [ ] Design increment
  - [ ] Composer has an L0 menu?
  - [ ] DXOS button?
