### ISSUE TITLE
API/protocol versioning

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3278]
Currently the HALO Vault and apps break on startup if either the protobuf schema or the core framework logic has changed.

To support Composer we critically need some subset of:

- [ ] Detect startup issue (HALO/ECHO stack surfaced to Client API).
- [ ] Report startup errors to Sentry (and notify user).
- [ ] Enable recovery from a local snapshot.
- [ ] Support hosting of multiple versions (e.g., read-only until upgrade).

**Comment by wittjosiah** [comment]
Preliminary thoughts:
- on testing
  - client tests on snapshots as a baseline for incompatible storage
  - e2e composer tests of main running against older versions of halo to detect incompatible apis
  - e2e invitations between current and down-level halo versions
- "read-only until upgrade" sounds a little oppressive, in case of incompatibilities, if you don't want to upgrade from an incompatible version you should be able to go into "hermit mode" and not sync with peers who have upgraded (e.g., current version should work indefinitely and not break because upgrades were released which is not a great experience)
- it would be helpful to enumerate all the places we imagine incompatibilities might arise so that we can walk through failure (and ideally recovery) scenarios for each. This will be important for detecting issues in such a way that the user can be appropriately notified and probably help with reporting as well.
