### ISSUE TITLE
MS: Next SDK milestone draft

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#333]
- [ ] File store
  - [ ] ChromeFS
- [ ] Version storage https://github.com/dxos/protocols/issues/227
- [ ] Make bots great again
- [ ] Gravity & bots
- [x] #332
- [x] #328
- [x] #260
- [ ] Security
  - [ ] Web crypto API
- [ ] Wallet
  - [ ] UX adjustments
  - [ ] E2E tests for wallet background process
  - [ ] Keyhole auth
  - [ ] Make it work with existing kubes
  - [x] #321
- [ ] Safari support
  - [ ] Support and test IDB
  - [ ] Client tests for safari
