### ISSUE TITLE
Remote Functions Prototype

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3363]
# Remote Functions

https://github.com/dxos/dxos/issues/3205

- [x] Basic gateway connector
- [x] Fork https://github.com/pawelotto/openfaas-node16-typescript
  - [ ] Create base class to construct Client and provide in context
- [x] Chess function
- [ ] Automate config
- [ ] Namespace for functions (e.g., `org.dxos/function/chess`).
- [ ] Construct trigger from Kai
- [ ] Export typescript defs
