### ISSUE TITLE
Paper key recovery

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3365]
- [ ] API
  - [ ] Key phrase generation
  - [ ] Admit device via key phrase
  - [ ] Revoke key
- [ ] HALO Vault
  - [ ] Generate key
  - [ ] Recover via key
