### ISSUE TITLE
Personal Remote Agents MVP #1

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3366]
## Objective
All of DXOS team has an agent online for at least 60% of a week.

We provide instructions on how to run an agent using the CLI, with optional instructions on how to deploy a DO droplet that has the DX CLI pre-installed within our DO account for those that do not have an existing stable runtime environment

Realtime and asychronous support is expected and desired, with the goal for this to be self-service.

## Desired side effects
* DX CLI gains stability and maturity, we begin to think of the CLI commands and options as a stable API that may be consumed by both scripts and humans
* We have a test mule/tooling that we can conduct other experiments on
* We gain understanding of the comfort and preferences for running an agent of increasingly non-technical people

## Bonus points
* [Anyone can trigger an epoch (with OOB coordination)](https://github.com/dxos/dxos/issues/3923)
* CLI can notify the user when it needs to be updated
* We can distribute pre-beta versions of the CLI without having to git clone/build
* CLI-initiated backups to flat files (that could be run out of cron)

## Contrariants
* This is unlikely to be the final shape of an agent for end-users, so we need to polish it to the point where it's consumable by our entire team, but not any further.
* We should not over-invest in runtime management and orchestration, asking everyone to take some manual steps should be OK

## Definition of Done
* There is a README.md that explains how to deploy and run the agent
* We've collected data (manually or otherwise) to show the uptime of the agents within a 40% margin of error
* We've collected feedback from our users on their experience running their own agent

## Feedback/Known issues
- [ ] https://github.com/dxos/dxos/issues/3680
- [ ] https://github.com/dxos/dxos/issues/3740
- [ ] https://github.com/dxos/dxos/issues/3899

## Tasks

```[tasklist]
### Tasks
- [ ] Agent documentation https://github.com/dxos/dxos/issues/3605
- [x] Digital Ocean Droplet automation
- [ ] Agent timeseries data, logs, and crashdump management (see https://github.com/dxos/dxos/issues/3989)
- [ ] https://github.com/dxos/dxos/issues/3550
- [ ] https://github.com/dxos/dxos/issues/3507
- [ ] Client telemetry for this experiment
- [ ] Authenticated agent remote control (e.g. Each agent exposes ws://127.0.0.1:4567 (with unique port, only local host); dx agent devtools opens devtools inside browser)
- [ ] Simplify process to deploy and join HALO on remove host
```

```[tasklist]
### Tasks
```
