### ISSUE TITLE
The new AppKit

### ISSUE THREAD

**Issue by rzadp** [dxos/dxos#343]
# Tasks
- [x] Remove `material-ui` from `react-client`, and clear state must not have this dep. 
  - [ ] Prevent deps in CI?
- [ ] Create `react-framework` and move components from `react-ux` and `react-appkit`
  - [x] Move to here all components used by HALO extension
  - [x] Move to here all components used by `tasks-app`
    - [x] Merge RedeemDialog 
  - [x] Change deps in `tasks-app`
- [x] Deprecate `react-ux` and `react-appkit`
  - [x] Change Braneframe to use new framework.
  - [x] Move deprecated packages to braneframe monorepo (i.e., out of protocols)
- [ ] Evolve `react-appkit` into `braneframe-ux` (RB signoff req. on new name)

# Spec
1. Move HALO to browser extension - https://github.com/dxos/protocols/issues/68
    - It needs to be built on top of a public library because application would re-use same components in a extension-less mode
    - This library would inherit mostly the `react-ux`, `react-client`, and some of `react-appkit` components & hooks.
    - Functionality:
        - Profile management
        - Device management
        - Invitations
2. Develop Braneframe SDK / AppKit
    - These would be components & hooks for building Braneframe-like applications (or plugins/pads/frames for Braneframe). It would inherit the rest of `react-appkit` components & hooks.
    - Functionality:
        - ...
3. Figure out an interface for Pads/Frames
    - Is this gonna be in the same place as `2.`?
    - The interface needs to be very minimal but infinitely extensible - we cannot anticipate all of application building needs.

---

## Rules

- `@dxos/client` - no React!
- `@dxos/react-client` - depends on React, but no Material!
- `@dxos/react-framework` - depends on React and Material

---

## Questions

- Is Pad/Frame a DXOS thing or a Braneframe thing?

---

## Minimal set of required components

- `RedeemDialog` (configurable to be pinless)
- `JsonTreeView`
- `RegistrationDialog`
- `PartySharingDialog`
- `ClientInitializer`
- `ErrorBoundary`
- `useClient`, `useParty`, and other basic hooks
- Lower level hooks like `useInvitation`, `useInvitationRedeemer`
- Optionally: `MemberList` and `usePartyMembers`
- `BotDialog` and `useRegistryBots`, `useRegistryBotFactories`
