### ISSUE TITLE
[shell] panel design update

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3439]
This is about finishing the work we started on a design iteration of the panels that I never finished and could use help with whenever we get to this. 
```[tasklist]
### Tasks
- [ ] QR one-up views for space & device invitations
- [ ] Connectivity menu below profile in heading of IdentityPanel
- [ ] UI treats device invitations as singletons
```
