### ISSUE TITLE
Agent MVP tasks

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3507]
## Background
- Users will run an agent (locally or on hosted infra) joined to their HALO
- The agent can be configured to manage epochs
- Users will either run a single agent or designate one to be the leader (prior to leadership election functionality)
- Leader agents are responsible for managing epochs for Spaces that were created by the User (to avoid contention between agents from multiple members)

## Tasks
- [x] Peers should only request/download LAST epoch
- [x] Update heuristic to trigger epochs
- [x] Document start and join flows https://github.com/dxos/dxos/issues/3605
- [ ] Telemetry
  - [x] Uptime
  - [ ] Install event

#### Feedbacks
- [ ] https://github.com/dxos/dxos/issues/3680
- [ ] https://github.com/dxos/dxos/issues/3740
#### Stability
- [x] Lock file https://github.com/dxos/dxos/pull/3634
   - [x] Check if it works on MacOS and Linux
   - [x] Integrate 
- [x] Print start errors (wait for system service RPC)
- [x] Make `dx config` show config with defaults
- [ ] Each agent exposes ws://127.0.0.1:4567 (with unique port, only local host); `dx agent devtools` opens devtools inside browser  
#### Duplicates
- [x] `dx halo join` and `dx device join`
- [x] `dx debug echo-test-data` and test plugin inside labs.dev.dxos.org
#### Future
- [ ] Devices presence
- [ ] Devices metadata

## Product
- [ ] Simplify process to deploy and join HALO on remove host

## Future
- [ ] Leadership determined via credential
- [ ] Epoch snapshot time-travel
- [ ] Paper key recovery
- [ ] Leadership election

**Comment by nferch** [comment]
Should be mostly deprecated in favor of https://github.com/dxos/dxos/issues/4376
