### ISSUE TITLE
Agent lock file

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#3514]
```[tasklist]
### Tasks
- [x] Add node lock
- [x] Fail agent start gracefully if lock already in use
- [x] Reset lock on `dx reset` command
```

**Comment by mykola-vrmchk** [comment]
https://github.com/dxos/dxos/pull/3513
