### ISSUE TITLE
[composer-app] Cleanup tracking issue

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#3543]
- [x] remove react router & stop rendering layout based on route
- [x] abbreviate space keys in url
- [x] url encoding for file names
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
  - `.` is not encoded but also the browser seems to undo encoding after manually encoding it
- [x] fix disabled state in tree view leaves
- [x] make plugins closures
- [x] how to integrate with other object types?
- [x] basic code cleanup to reduce the amount of code in plugin files
- [x] DXN spec + update usage of all plugin ids
- [x] look for observable-object patterns to simplify
- [x] factor plugins out of composer-app
- [x] migrate datums from tuples to keyed objects
- [x] missing status orb from before extensibility

### Infrastructure Roadmap Draft

- [x] generic actions/intents system separate from the graph (#3672)
- [x] recursive interplugin graph annotation
  - enables generic space plugin
  - enables inspector plugin
