### ISSUE TITLE
Kanban plugin

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3555]
## Tasks
- [x] Draggable columns
- [x] Draggable items
- [ ] Drag items across columns
- [ ] Plugin graph
- [ ] Create ECHO objects

# Phase 2
- [ ] Config sortable/fixed query
- [ ] Custom properties
- [ ] Undo
- [ ] Auto-expand textarea rows

## PRs
- https://github.com/dxos/dxos/pull/3553

## Aurora notes
- [ ] Dragging style (relative z-index)
- [ ] Dragging craziness when at end of scrollarea
- [ ] Standards for panel colors
- [ ] Standards for plugins (e.g., title area)

**Comment by richburdon** [comment]
## Background
- Plugins currently "sniff" an array of objects and "offer" a matching component.
- Complex pure components define reactive models that provide data and methods.
- Observable (objects and arrays) enable reactive components.

## Issues
- How should the plugin construct models that are presented to the component.
  - Currently the outer "main" component would need to construct the model and pass that to an inner component.
  - How can a test/story environment configure this outer component to implement a specific model type (e.g,. ECHO vs. faker).
- Should complex models be interfaces that contain reactive observer objects?
