### ISSUE TITLE
DXOS is stable enough to dogfood our apps

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#3610]
# DXOS platform is stable enough for DXOS the company to dogfood our own apps

# Current State
- Composer is an impediment for Business As Usual (slow cold start, unstable invitations, slow replication, etc. link list of known issues)
- Unclear urgency for repair which leads to slow time to repair
- Immature diagnostic and observability capabilities make issue diagnosis difficult and limited to subset of team
- Unclear, incomplete, and inconsistent reports of prod issues (e.g. https://github.com/dxos/dxos/issues/3506)

# Shape of Solution
- Documented and Observable flow for managing prod issues (shared with S2O4)
- Runtime observability capabilities
- Testbench observability capabilities (TODO: details)
- Known protocol/library issues scoped and prioritized (TODO: populate and scope list)

## Runtime observability capabilities

Tasks:

- https://github.com/dxos/dxos/pull/3698
- https://github.com/dxos/dxos/pull/3656
- https://github.com/dxos/dxos/pull/3686
- https://github.com/dxos/dxos/pull/3682
- https://github.com/dxos/dxos/pull/3664

## Testbench observability capabilities

- Testsbench verifies protocols stability envelope
- Multiple levels of testing

### ECHO testing

- Tests database, epochs, replication, invitations
- Allows us to measure ECHO scaling boundaries
  - - Number of peers in the space: writers/readers
  - - Size of spaces: number of objects, size of objects, yjs/document CRDTs
  - - Number of spaces per peer: active/inactive
  - - Mutation throughput: how many active writers can we support?
  - - Epoch frequency, replication speed
  - - Conflict resolution: mutation-based (CRDT, total oredering); epoch-based: rebasing, branching, time-travel;

Tasks:

- https://github.com/dxos/dxos/pull/3688
- Cannot re-activate spaces after they have been deactivated in the same session
- https://github.com/dxos/dxos/pull/3661

### Network testing

Main issue: 

- https://github.com/dxos/dxos/issues/3515

Tasks:

- https://github.com/dxos/dxos/issues/3701
- https://github.com/dxos/dxos/pull/3633
- https://github.com/dxos/dxos/pull/3644
- https://github.com/dxos/dxos/issues/3668 [P1]

### Singaling testing

- Simulates N signal-servers with M clients
- Tests peer discovery
- Tests peer messaging

### Tasks [P0]

- [x] https://github.com/dxos/dxos/pull/3601
- [ ] https://github.com/dxos/dxos/issues/3619
- [x] Verify connection limiter is working (releated to devtools Connection view)
- [ ] #3922  @dmaretskyi
- [x] #3911
- [x] `Error: Properties not found.`
- [ ] #3913

### Tasks [P1]

- [ ] https://github.com/dxos/dxos/issues/3515
- [ ] Large number of closed connections visible in devtools [P1]
- [ ] #3910 [P1]
- [ ] https://github.com/dxos/dxos/pull/3909 [P1]

**Comment by jessmartin** [comment]
@nferch I think this can be closed or at least un-pinned and perhaps renamed. What say ye?
