### ISSUE TITLE
DXOS stability doesn't detract from initial adoption

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#3611]
# Summary
As we begin to market and socialize our platform, we don't want any blockers or serious impediments that detract from adoption or community engagement.

For example, a visitor should be able to complete the Getting Started guide with little frustration.

Compared to O5 ("DXOS platform is stable enough for DXOS the company to dogfood our own apps"), the stakes are higher but the surface is lower. As such, the shape of our solution is likely to be more rigorous and repeatable.

# Shape of Solution
- We have documented agreement (Stakeholders: Jess & Rich) on what the three* most important flows and functionality are for initial adoption
- We have at least one quantitative measure of normal for each of the three* most important flows
- We can automatically measure at least one* of the most important flows
- Documented and Observable flow for managing prod issues which can handle automated alerts based on an automated alert or human input (shared with S2O5)

* Exact targets TBD

# Desired side effects
- We gain understanding of our Getting Started guide and consider ensuring it's aligned as a part of our engineering methodology
- We improve our e2e testing and automation capabilities
- We learn more about the failure modes of our platforms and how our APIs, CLIs, and libraries respond to unexpected contexts and inputs

# Critical Tasks
* "Fail whale" for app crashes - Hard crash, black screen (which shouldn't happen). Soft crash, e.g. spaces not loading. (Nathan)
* Existing e2e test suite for getting started? (Nathan)
* Procedure for responding to e2e test breakages (Nathan)
```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/issues/3618
- [ ] https://github.com/dxos/dxos/issues/3619
- [ ] https://github.com/dxos/dxos/issues/3620
```
