### ISSUE TITLE
[product] July milestone

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3624]
- josiah
  - [x] plugins collaborate on graph building
  - [x] bundle size reduction
  - [x] tech debt
  - [x] local files appear in composer
  - [x] clear security warnings in sdk
  - [x] composer intents model

- will
  - [x] basic stack
  - [x] global drag and drop
  - [x] drag from sidebar to stack
  - [x] shell panel debt reduction
  - [ ] drag objects between spaces

- zhenya
  - [ ] composer specs and ux
  - [ ] halo specs and ux
  - [ ] sdk specs for personal space api
  - [ ] sdk specs for progressive multiplayer
  - [ ] roadmap
  - [ ] land plate upgrades (fix CLI warnings and errors)
  - [ ] 2 min video
  - [ ] define composer performance KPIs
