### ISSUE TITLE
[devrel] July Milestone

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#3625]
# July 2023 Milestone

**Objective: Feedback gathered from 10 developers have built anything with DXOS by July 31, 2023.**

Definintions:
- "Feedback gathered" - we talked to the developer and learned from them what went well, what could be improved.
- "built anything with DXOS" - developer not employed by DXOS used the DXOS React or TypeScript SDK directly.

Leading Metrics:
- 100+ blog subscribers
- 100+ followers on Twitter account
- GitHub `dxos` project has 100+ stars and/or `dxos` organization has 100+ followers
- 1000+ views of DXOS video content
- Docs answer many, but not all questions (60% of the time, able to answer questions with docs)

## DevRel "good hygiene"

- Regular social updates
    - RESULT: regular social updates started on July 25
    - see #3745 
- 1 blog post a week
    - RESULT: 2 blog posts total
- Monthly newsletter of project updates
    - RESULT: coming out first week of August

## Meet with people 1-to-1

- [x] Future of Code meetup in NYC
- [x] Jess meeting with 5+ developers per week
   - [x] Week of July 3: 4 meetings
   - [x] Week of July 10: 12 meetings
   - [x] Week of July 17: 4 meetings
   - [x] Week of July 24: 3 meetings
- [x] Support developers building in Discord

## Build working examples

- [x] Build kanban/todo/composer demo showing different apps interacting
- [ ] Agent demo
- [ ] Show off building a plugin in Composer (video)

## Publish reports from the Lab

- [ ] Composer extensibility blog post (in-progress)
- [ ] Kai demo video
- [ ] About epochs

**Comment by richburdon** [comment]
Ideas
- Matrix of features/readiness; ROADMAP (HALO app, ECHO spaces/db/epochs, CLI, KUBE+signaling, Agents, Plugins)
- Value proposition
- Devtools stats (API, devtools, kube, CLI, docs)
- Tools/getting started (create app/plugin from template)
- Composer/HALO stats; Typeform survey
- Plugins roadmap
- Bi-weekly AMA
- Hiring

**Comment by jessmartin** [comment]
Stats as of 7/28:
- 7/100 blog subscribers
- 78/100 followers on Twitter account
- 27/100 stars on `dxos/dxos`
- 26/1000 views of DXOS video content
- Docs answer many, but not all questions (60% of the time, able to answer questions with docs)

Will update on 7/31 will final stats.
