### ISSUE TITLE
[product] Aug milestone

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3685]
protocols:
- [ ] instant cold start
  - [ ] start / stop spaces
- [ ] benchmark 20-50 users collaborating
- [ ] paper key recovery
- [ ] invitations
  - [ ] pin-less
  - [ ] expiry duration
  - [ ] multiple-use
  - [ ] known contacts (P2)
  - [ ] offline (P3)
- [ ] everyone is running agents on their machines
- [ ] begin threat modeling

sdk:
- [ ] cold start telemetry
- [ ] personal space APIs
- [ ] progressive multiplayer store
- [ ] shell panels support new workflows (progressive store, single device invitation, non-accordion invitations)

composer:
- [ ] new OOB experience (personal space, progressive MP)
- [ ] visual facelift
- [ ] sidebar nesting
- [ ] lazy graph expansion
- [ ] halo button
- [ ] drag and drop local files and echo spaces
- [ ] drag and drop objects between spaces
- [ ] datagrid, GH intelligence scenario
- [ ] global drag and drop stability
- [ ] stacks present folders / group nodes by default

cli:
- [ ] clear security vulnerabilities warnings
- [ ] join HALO (device)

docs:
  - [ ] docs fast publish
  - [ ] docs sandbox

halo:
- [ ] ux facelift, shell panels, join device flows work (P0)
- [ ] fast CLI join flow (protocol invocation) (P1)
- [ ] data export features (P2)
- [ ] data browser features (P3)

labs:
- See #3768 

website:
- [ ] revamp overall messaging
- [ ] composer marketing

---

Sept planning:
- [ ] search
- [ ] threads
- [ ] contact list in halo
- [ ] devtool upgrades
- [ ] authorization and security model?

Not thinking about:
- [ ] functions
- [ ] agent multitenancy / appliance
- [ ] kube
- [ ] kanban

---

See also 
- [ ] #3624

**Comment by zhenyasav** [comment]
- polish the look and feel of our website / docs / marketing pages

**Comment by zhenyasav** [comment]
closing in favor of #3869
