### ISSUE TITLE
[product] strangeloop checklist

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3869]
## Strange Loop Checklist

[Strange Loop](https://www.thestrangeloop.com/index.html) Sept 21

## Features

Minimum target: All P0 items.
Ideal target: All P0 and P1 items.

These are now in priority order within each feature area.

Schedule estimates in comment below.

### Apps
- [x] #3844
- [x] #3876
- [ ] [composer] grouping of issues and documents in the sidebar tree (align with Figma spec)
- [ ] [composer] main window <title> should change to title of active document
- [ ] #3886
- [x] #3887
- [x] #3863
- [ ] #3901
- [x] #3854
- [x] #3868
- [x] #3906
- [x] #3905
- [ ] [composer] infer document title from first H1
- [ ] [composer] fix "current app name is ready to use offline" to "Composer is ready to use offline".
- [ ] [composer] restore and upgrade main app loading indicator
- [ ] #3832
- [ ] [composer] increase font sizes for phones and ipads
- [ ] [composer] startup error boundary (e.g., fail to load vault, Firefox)
- [ ] #3914
- [ ] [cli] new composer with plugins app template
- [ ] [[cli] fix security vulnerabilities in CLI](https://github.com/dxos/security/issues/9)
- [ ] [composer] facelift for composer
- [ ] [composer] redesign the empty state hints
- [ ] #3904 @richburdon - week of 8/14

### Platform
- [ ] #3862
- [x] #3845
- [x] #3935
- [ ] #3861
- [ ] [client] replication bugs, replication slowness
- [x] #3874
- [x] #3889
- [ ] #3828
- [ ] #3924
- [x] #3922

### DevRel
- [ ] #3902 @jessmartin - week of 8/14
- [ ] #3912 @jessmartin - week of 8/14
- [ ] [docs] what works and what doesn't - limitations for the platform @jessmartin - week of 8/21
- [ ] [docs] shell documentation @jessmartin - week of 8/21
- [ ] [website] demo of the product in action @jessmartin - week of 8/21
- [ ] [blog] State Management @jessmartin - week of 8/21
- [ ] [website] scenarios two or three things you can do with it
- [ ] [website] website upgrade
- [ ] [docs] demo talk tracks for strange loop
- [ ] [blog] Shipped in August (monthly thing we did) (T-2)
- [ ] [blog] Plugins post (T-1)
- [ ] [blog] Agents (?)
- [ ] [docs] roadmap - big ticket items (rework the plugins API, rework the graph API, plugins, specs, release changelog)

### Plugins
- [ ] [stack] allow dropping elements at the end of a stack
- [ ] [stack] visual facelift to match spec
- [ ] #3877
- [ ] [docs] getting started with building plugins
- [ ] [thread] show thread for each item in right sidebar
- [ ] #3883
- [ ] [thread] show standalone threads as channels
- [ ] [thread] parse ChatGPT replies into paragraphs and JSON blocks as separate messages

### Apps

- [ ] [shell] scrollbar too huggy
- [ ] #3839
- [ ] [composer] toast comes up when an invitation is ready for a pin code
- [ ] [composer] vim shortcuts for moving lines up and down
- [ ] [composer] toast with invitation ready showing pin code directly in toast
- [ ] #3882
- [ ] [composer] restore support for editing files on disk
- [ ] #3852
- [ ] [composer] add an app version number in the settings area of composer
- [ ] [composer] breadcrumbs at the top of main
- [ ] [composer] show progress indicators when loading spaces
- [ ] #3840
- [ ] #3865
- [ ] [composer] presence in the top right corner of the document
- [ ] [shell] auto-dismiss end success states
- [ ] #3872

### Plugins

- [ ] [stack] dialog to insert existing objects into the stack on mobile
- [ ] [labs] Presenter plugin
- [ ] [stack] expand item to fill main area, go back to stack view
- [ ] [stack] create new stack by expanding one card into it's own stack (forward nav) and nav backwards to original stack
- [ ] [stack] show list of stacks an item is contained within in the right sidebar

### DevRel

- [ ] [samples] chess app playing against ChatGPT opponent

### Apps
- [ ] [hubposer] editing an issue can end up showing stale state in ECHO
- [ ] [composer] cmd + K to jump anywhere
- [ ] [composer] actions grouping to group all create actions
- [ ] [composer] folders for documents in sidebar tree
- [ ] [composer] rich text editor without visible markup symbols
- [ ] [composer] popover for renaming a space sits next to the tree item
- [ ] [composer] enter dismisses the rename popover
- [ ] [composer] jumpy selection when other peoples presence moves around
- [ ] #3867
- [ ] [composer] translucent selection
- [ ] [composer] add an app deploy date in the settings area next to version number
- [ ] [shell] supports pin-less invitations
- [ ] [shell] supports multi-use invitations
- [ ] [shell] show loading state after auth code entered
- [ ] [composer] presence in the sidebar S0

### Plugins

  - [ ] [stack] expand item to fill main area, go back to stack view
  - [ ] [stack] create a new card stack by expanding one card into it's own stack (forward nav) and nav backwards to original stack
  - [ ] [stack] show list of stacks an item is contained within in the right sidebar

### Platform

- [ ] Dedup connections to a single peer under different swarms
- [ ] #3923

## Cut
- [ ] two way sync with local files

## Background

Strange Loop is a big opportunity to show off what we're working on:
- ~1700 developers at the main conference on Thursday/Friday, interested in our technology. Lots of talks relating to stuff we're working on.
- All-day Saturday [local-first unconference](https://lu.ma/localfirstswunconf-stlouis) led by Martin Kleppman, PVH of Ink and Switch, and Brooklyn Zalenka of Fission.
- Jess, Josiah, Dima, and Rich will all be on-site.

**Comment by zhenyasav** [comment]
### Week T-5 (Ending Aug 18)

### Week T-4 (Ending Aug 25)

### Week T-3 (Ending Sept 1)

### Week T-2 (Ending Sept 8)

### Week T-1 (Ending Sept 15)
