### ISSUE TITLE
Table plugin

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3927]
## Purpose
- Able to build CRM (lists/cards).
- Plugin displays a configurable table of ECHO objects.
- Able to render in stack section.
- Able to export objects from chat (e.g., OpenAI function) into stack.

## Tasks
- [ ] Query items based on type; update `Expando` API.
- [ ] Add/remove columns with popover (name, prop, type).
- [ ] Add/remove rows (with undo/view deleted).
- [ ] Select column types.
- [ ] Column reference (to other schema)
- [ ] Infer table columns from TypedObject properties.
- [ ] Stack section.
- [x] Schema type definition.
- [x] Column resizing

## ECHO
- [ ] useQuery not updated when objects deleted.
- [ ] create `Expando` with `__typename`.
- [ ] Expando schema (objects with ID of schema, but represented as queryable reference).
- [ ] push/slice/update arrays.
- [ ] update property of array member.
- [ ] Protobuf generated `__typename`
- [ ] `record<string, string>`

Will:
- [ ] Dragging/resizing
- [ ] Theme
- [ ] Focus/selection

## Progress
- https://github.com/dxos/dxos/pull/4108
- https://github.com/dxos/dxos/pull/3926
- https://github.com/dxos/dxos/pull/3928
