### ISSUE TITLE
Evaluate migration to hypercore 10

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3977]
## Rationale
- Current replication with v9 causes each block to be written individually to storage which creates a file IO bottleneck.

## Tasks
- [x] Evaluate v10 deps (e.g., RAS)
- [ ] Update basic feed-store tests to migration effort
- [ ] Create replication test to determine efficacy of moving to v10

## PRs
- https://github.com/dxos/dxos/pull/3958

## Conclusion
- v10 does not support Noise protocol in the browser -- decide to pause.
