### ISSUE TITLE
Mitigate currently known performance bottlenecks in browser

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3980]
Re: https://github.com/dxos/dxos/issues/3802

Current state:

```
5,000 mutations
100s time to replicate
1M feed storage
2M data replicated over network
average throughput 20K/s
startup time 5s (1000 TPS)
```

Target state:

* 5x faster startup (space startup time in Labs Debug diagnostic)
* 10x faster replication 

## Tasks
- [ ] [Optimize startup latency (file IO); contingent on improvements to file IO (e.g., adjustment to WebFS API).](https://github.com/dxos/dxos/pull/4024)
- [x] [Assess migration to Hypercore v10.](https://github.com/dxos/dxos/issues/3977)
- [x] Assess WebFS sync. API: https://github.com/dxos/dxos/pull/4024
  - Does not support web workers

**Comment by dmaretskyi** [comment]
webfs-async 10ms read, 30ms write, 1kb chunks

**Comment by dmaretskyi** [comment]
Flushing ON:
```
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:49:07.210Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 1,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 130,
    numWrites: 130,
    realRunTime: 3320.100000023842,
    avgReadTime: 0.06769230732550988,
    avgWriteTime: 25.456923076739677
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:49:11.163Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 5,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 160,
    numWrites: 160,
    realRunTime: 3947.0999999046326,
    avgReadTime: 0.05625,
    avgWriteTime: 111.28875000029802
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:49:16.137Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 10,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 230,
    numWrites: 230,
    realRunTime: 4970.699999928474,
    avgReadTime: 0.11434782432473224,
    avgWriteTime: 173.63521739140802
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:49:22.917Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 20,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 340,
    numWrites: 340,
    realRunTime: 6778.200000047684,
    avgReadTime: 0.16117647079860462,
    avgWriteTime: 292.35000000035063
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:49:31.943Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 30,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 440,
    numWrites: 440,
    realRunTime: 9022.5,
    avgReadTime: 0.1284090911800211,
    avgWriteTime: 411.69590909183023
  }
}
```

Flushing OFF:

```
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:50:34.914Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 1,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 35530,
    numWrites: 35530,
    realRunTime: 3000.2999999523163,
    avgReadTime: 0.03951590211163968,
    avgWriteTime: 0.04391218679843068
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:50:38.047Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 5,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 41430,
    numWrites: 41430,
    realRunTime: 3128.5,
    avgReadTime: 0.04021240648600666,
    avgWriteTime: 0.3339415882136147
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:50:41.088Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 10,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 40170,
    numWrites: 40170,
    realRunTime: 3010.3000000715256,
    avgReadTime: 0.037545431983806256,
    avgWriteTime: 0.7058849887109556
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:50:44.107Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 20,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 43040,
    numWrites: 43040,
    realRunTime: 3017.600000023842,
    avgReadTime: 0.035666821570201436,
    avgWriteTime: 1.3600185873533934
  }
}
{
  params: {
    environment: 'chromium',
    date: '2023-08-29T15:50:47.137Z',
    type: 'webfs-blocking',
    DATA_SIZE: 1024,
    NUM_THREADS: 30,
    NUM_READS: 10,
    NUM_WRITES: 10,
    RUN_TIME: 3000
  },
  result: {
    numReads: 42350,
    numWrites: 42350,
    realRunTime: 3023.2999999523163,
    avgReadTime: 0.0359551358110367,
    avgWriteTime: 2.0939409680602963
  }
}
```
