### ISSUE TITLE
Misc connectivity issues

### ISSUE THREAD

**Issue by egorgripasov** [dxos/dxos#4013]
Currently we are experiencing a number of connection-related issues which is resulting in various connection-stuck symptoms;
3 groups of things so far (in order of significance):

1. Spammy signal server. This most likely does not create big issues, but can contribute to the overall problems;

2. Whatever we do with race conditions / concurrent connections. This is the case when 2 peers are trying to connect to each other simultaneously, and it seems we have some problems in handling such connections; Before the connection limiter we were most likely "saved" by artificial (small) timeout we put in one peer based on the if (remoteId.toHex() < this.localPeerId.toHex()) condition, so it would wait till the other peer connects first; Now the order is non-deterministic and seems like it happens bit more often, so I would like to make sure we properly manage those connections (seems like some of them might stuck in connecting state and also in connection-limiter)

3. PeerLeft is not coming through during the testing - this seems to be the big/main problem, it cause peer to keep to reconnecting to other peer even if it's already succeeded with the invitation, which also results in stuck connections;

We all might see different symptoms based on the combination of this issues (and potentially other unknown issues). It makes sense to go over them and try to fix all we know is broken, so after it we could re-evaluate the networking state and see what's fixed and what's still acting weird.

We believe these issues are the source of the symptoms seen in https://github.com/dxos/dxos/issues/3975 and https://github.com/dxos/dxos/issues/3951 but need to test and investigate further.

For each fix corresponding test should be created, which will be broken as is, and working after fixing the problem.

```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/issues/4058 (P2)
- [ ] https://github.com/dxos/dxos/issues/4059
- [ ] https://github.com/dxos/dxos/issues/4060
```
