### ISSUE TITLE
long running agent test

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#4142]
# Motivation
* Generate some data to better understand the limits w/r/t https://github.com/dxos/dxos/issues/3862 (i.e. 10 members * 5 devices = 50 concurrent peers)
* Better understand how the networking and stack overall behaves with long-running clients
* Better simulate real-world usage (agents leaving and joining swarms over time)

```[tasklist]
### Tasks
- [ ] Modify testbench to support additional test conditions and long-running test
- [ ] Share initial data and findings
- [ ] Manually run testbench on the order of hours
- [ ] Create infrastructure and orchestration to run testbench autonomously and write output somewhere
```
