### ISSUE TITLE
[Tracking] Long lived testing fixes

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#4178]
Tracking issue for ongoing fixing/investigation from https://github.com/dxos/dxos/pull/4172

# Memory Leaks

```[tasklist]
### Tasks
- [ ] Agent OOM errors
- [ ] Testbench OOM errors
- [ ] https://github.com/dxos/dxos/issues/4181
```

# Networking

```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/pull/4175
- [ ] Test using TCP transport
- [ ] https://github.com/dxos/dxos/issues/4174
- [x] Repeat test once connectivity fixes are merged (https://github.com/dxos/dxos/issues/4058 https://github.com/dxos/dxos/issues/4112 https://github.com/dxos/dxos/issues/4127)
- [ ] https://github.com/dxos/dxos/issues/4203
- [ ] https://github.com/dxos/dxos/issues/4204
- [ ] https://github.com/dxos/dxos/pull/4211
- [ ] https://github.com/dxos/dxos/pull/4216
- [ ] https://github.com/dxos/dxos/pull/4217
- [ ] https://github.com/dxos/dxos/pull/4232
- [ ] https://github.com/dxos/dxos/pull/4233
- [ ] https://github.com/dxos/dxos/pull/4234
- [ ] https://github.com/dxos/dxos/pull/4172
- [ ] https://github.com/dxos/dxos/issues/4013
- [ ] https://github.com/dxos/dxos/issues/4059
- [ ] https://github.com/dxos/dxos/issues/4060
- [ ] https://github.com/dxos/dxos/pull/4101
- [ ] https://github.com/dxos/dxos/pull/4139
- [ ] https://github.com/dxos/dxos/issues/4112
```

# Other / Unknown

```[tasklist]
### Tasks
- [ ] Minimal/no activity testing
- [x] Test replication failure with low number (1-4) of peers
- [x] Identify memory leaks from test setup
- [ ] https://github.com/dxos/dxos/issues/4202
- [ ] https://github.com/dxos/dxos/pull/4219
```

**Comment by jessmartin** [comment]
@nferch this looks like one of those mostly-done tracking issues that hangs around far too long. Can we close it and track the individual tickets now?
