### ISSUE TITLE
Device Management

### ISSUE THREAD

**Issue by rzadp** [dxos/dxos#433]
## User Story

The user has a profile in his CLI.
He authorises a device (e.g. a Halo Wallet extension, or another CLI for starters).
The CLI and the extension is then the same person.

This flow will be required for progressing https://github.com/dxos/protocols/issues/68 further.

## TODO

- [x] Add Device Invitations to `cli-data`
    - [x] Without persistent storage
    - [x] With persistent storage
- [x] Add Device invitations to Wallet extension
- [x] Integrate CLI -> Wallet invitations

## To design

The DXNS credentials should be stored in HALO and synced between profiles, in order for the user to be able to invite another device and publish apps under the same identity.
