### ISSUE TITLE
Agent Roadmap

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#4376]
# Desired Results
* 100 agent MAU
* Stabilize agent running continuously under real world conditions
* Gain customer signal on the desired shape of solution for agent
* Improve customer engagement on the DXOS platform
* Bootstrap DXOS social network

# Milestone 1: All DXOS team running agents
Everyone on the DXOS team is running an agent on a managed Digital Ocean droplet or their own system, with some minimal observability to prove this is the case.

# Milestone 2: Agent CLI tech preview
We have announced a tech preview for agents that can be run on the CLI on a user's system. 

Audience: Targeting savvy early adopters who have or can configure a system that can run the agent.
Shape of solution: A minor evolution of our existing CLI, with the minimal changes necessary to make incremental progress toward our desired results.

```[tasklist]
### P1
- [ ] https://github.com/dxos/dxos/issues/4352
- [ ] https://github.com/dxos/dxos/issues/4411
- [ ] https://github.com/dxos/dxos/issues/4410
- [ ] https://github.com/dxos/dxos/issues/4394
```

# Milestone 3: One click agent tech preview
Audience: Developers with less experience running systems in production who want a simple way to run an agent with minimal fuss.

Shape of solution: We have a minimal one-click to deploy solution for agents. Could run on our own infrastructure and provide operational management if it's easier for us. Not (necessarily) intended to be an ongoing service, but an experiment to collect customer signal.

```[tasklist]
### P1
- [ ] Agent 2.0 lifecycle and packaging
```

# Out of the critical path
* Networking topology/mobile connectivity
* Identity, address book
* Signalling architecture

**Comment by nferch** [comment]
Closing in favor of https://github.com/dxos/dxos/milestone/11 and https://github.com/dxos/dxos/issues/4843
