### ISSUE TITLE
20p network stability target

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4492]
- [ ] 20 identities, 1 device per identity
- [ ] Multi-use, auth-code-less invitation
- [ ] Using desktop Chrome (and Safari)
- [ ] Fresh profile
- [ ] Broadband (or mobile) Internet
- [ ] Single space, < 20 documents
- [ ] automatic epoch not needed

Explicitly not supported:
* Mobile browsers
* Firefox

```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/issues/4377
- [ ] https://github.com/dxos/dxos/issues/4500
- [ ] https://github.com/dxos/dxos/issues/4501
```
