### ISSUE TITLE
Query types

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#4495]
### Query types

```ts
// Type based queries: static / dynamic schema
xxx.query(Task.filter({ name: 'test' }))

// predicate based queries
xxx.query(obj => obj.name.startsWith("John"))

// DNF/compound queries?
xxx.query(Filter.not(Filter.and(Filter.text('foo'), Filter.range('value', 0, 10))))

// Text queries
xxx.query(Filter.text('foo'))

// Specific verbs
const { objects: schemas } = xxx.query(Schema.filter())
xxx.query(Filter.schema(schemas[0]))
xxx.query(Filter, { ...options, from: QuerySource.REMOTE })

xxx.query(<serialized query proto>)

{
  object,
  match,
  confidence,
  resolution: {
    source: 'agent' | 'local',
    time: 123
  }
}


// Abstraction for space.db and hyperspace
interface Queryable {
  query(filter: Filter): Query<T>;
}

type QueryResult<T extends EchoObject> = {
  object: T;

  match?: {
    // text positional info
    
    rank: number // 0.95, 0.92, 0.72, ....
    
  },
  // query resolution metadata. 
  resolution?: {
    source: 'agent' | 'local',
    time: 123
  }
}


// too exotic...
type Query = T[] & { methods... }

// Weak semantics - no explicit finialization needed
interface Query<T> {
  // signal semantics
  get objects: T[]; // == results.map(result => result.object)

  // signal semantics
  get results: QueryResult<T>[];
  
  subscribe: () => SubscriptionHandle // TOOD: Resolve SubscriptionHandle vs Subscription

  // for remote queries
  // resend the query to the agent 
  update(): Promise<void>
}
```

- return array with subscription method? (signal?)

- query by schema
- compound filters: AND / OR
- full text match - text found in any field of an object, possibly approximate match
- range predicates IN, GT, LT (dates, numbers)
- graph traversal

### Schema

- fixed precision
  
- metadata for default label field
- metadata for indexing
- metadata for LLM

### API

- Symbols vs `__foo` vs `foo` vs `foo(obj)`
- Deprecate `meta.index`
- query scope (space, hypergraph, more?)
- client-agent

### Tasks

- [ ] Typescript api
- [ ] Protobufs to serialize queries and results; SearchService
- [ ] db.query should just map into graph.query
- [ ] Hook-up agent search to ECHO api
- [ ] Extract text indexing into client-services
