### ISSUE TITLE
CRM

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4533]
# CRM Use Case

## User stories

- Create tables that define types (e.g., Project, Contact, Interview)
- Enter Contacts and associated Projects (many-to-many)
- Create kanban to manage interview process (stage of candidate)
- Create grids with short list of projects/contacts
- Search across Spaces and drag rows between spaces (e.g., personal Space => shared KM)
- Search/crawl contacts from GH; drag results into table
- Create summary of candidate via OpenAI
- Import/export JSON/CSV

## Phase 1

- [ ] Table
  - [ ] Storybook/tests for schema editor
  - [ ] Storybook/tests for adding rows
  - [ ] Storybook/tests for Combobox
  - [ ] Sort/filter (add to View object)
  - [ ] Configure view added to stack
  - [ ] Drag row (drag from search)
  - [ ] Undo delete
  - [ ] Import CSV (map to schema)
- [ ] Grid
  - [x] Drag result from search
  - [ ] Drag document from sidebar
  - [ ] Use schema to lens properties of referenced objects
- [ ] Search: Hyperspace (client/agent)
- [ ] Basic mobile experience (find/edit cards)

## Phase 2 (experimental)

- [ ] Kanban
  - [ ] Port from mosaic
  - [ ] Select schema and column property
- [ ] Agent resolvers/syncing (GH)
