### ISSUE TITLE
Cross-package imports for the @dxos/protobuf-compiler

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#459]
Allow for imports from npm packages inside protobuf files:

```
syntax = "proto3";

package dxos.test;

import "@dxos/echo-protocol/src/proto/dxos/proto";
```

## Tasks

- [x] Implement name resolution be overrriding the protobuf.js resolver. Some work has been done in https://github.com/dxos/protocols/blob/main/packages/common/protobuf-compiler/src/parser/resolver.ts but it was never tested and probably doesnt work correctly.
- [x] Add a test for it. Perhaps have a proto file in `@dxos/codec-protobuf` and then have `@dxos/protobuf-compiler` tests import and use it.
- [x] (next-step) Consider adding a `protobuf` field to package.json to act in the same way as `main` and `types` work: specifying the "main" protobuf file. So for example if in package json `"protobuf": "./src/proto/dxos.proto"` then `import "@dxos/codec-protobuf"` would map to importing that proto file
