### ISSUE TITLE
[epic] Platform

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4840]
## M0 (Dec 2023)

- [ ] #4841
- [x] #4842
- [ ] #4843

## M1

- [ ] kube can run an agent
- [ ] kube can run a matrix relay
- [ ] kube can run an email bridge
- [ ] kube console

## M2

- [ ] kube separation from kubo / ipfs

## M3

- [ ] agent extensibility (functions)
