### ISSUE TITLE
[agent] standalone agent release

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4841]
## Motivation

Users should be able to install their own self-hosted agent. Install via the CLI.

## Finish Line

```[tasklist]
### Tasks
- [x] https://github.com/dxos/dxos/issues/4873
- [ ] https://github.com/dxos/dxos/issues/4408
- [ ] https://github.com/dxos/dxos/issues/4409
- [ ] https://github.com/dxos/dxos/issues/4824
- [ ] https://github.com/dxos/dxos/issues/4933
```

**Comment by nferch** [comment]
See https://github.com/dxos/dxos/milestone/11

**Comment by jessmartin** [comment]
@nferch I believe this is completely done. Can you confirm and close if it's the case?

**Comment by nferch** [comment]
@jessmartin there were some incomplete issues that were linked to the milestone that were removed. I re-added them to a tasklist above, do you consider any of those standing in the way of considering this complete?

**Comment by jessmartin** [comment]
Thanks for collecting those! It depends on what we mean by "release" above. I asked @zhenyasav for clarification on priority. I think before we announce the technical preview of the Agent via CLI we should probably fix the two bugs in the tasklist above.

**Comment by jessmartin** [comment]
Closing this as it's just a tracking issue of issues we're already tracking at the project level. Offers no additional value.
