### ISSUE TITLE
[agent] agent appliance prototype

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4843]
```[tasklist]
### P0
- [ ] https://github.com/dxos/dxos/issues/5066
- [ ] https://github.com/dxos/dxos/issues/5067
- [ ] https://github.com/dxos/dxos/issues/5068
- [ ] https://github.com/dxos/dxos/issues/5069
- [ ] https://github.com/dxos/dxos/pull/4454
- [ ] https://github.com/dxos/dxos/issues/5279
- [ ] https://github.com/dxos/dxos/issues/4378
- [ ] #6307 
- [ ] https://github.com/dxos/dxos/issues/6390
```
```[tasklist]
### P1
- [ ] #5907 
- [ ] https://github.com/dxos/dxos/issues/4884
- [ ] #6260
- [ ] #6259 
- [ ] #6261 
```
```[tasklist]
### P2
- [ ] #6309 
- [ ] #6229 
```

**Comment by jessmartin** [comment]
@nferch feel free to flesh out this by copy/pasting stuff over from the agent spec, as you need to.
