### ISSUE TITLE
[epic] sdk

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4844]
## M0

- [ ] #4834 
- [x] #4845
- [x] #4846
- [ ] #4847
- [ ] #4848
- [ ] #4757
- [x] #4849

## M1

- [ ] halo pinless invitations
- [ ] halo identity recovery
- [ ] halo device reset
- [ ] halo device revoke
- [ ] halo device rename

## M2

- [ ] type system
- [ ] search support
- [ ] partial replication support

## M3

- [ ] access control APIs

## M4

- [ ] BLOB APIs
