### ISSUE TITLE
[epic] composer

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4850]
# Composer roadmap

Feature areas prioritized:

- Authoring (+ comments on documents)
- Organization
- Sharing
- Commanding/Search
- Local files
- Whiteboarding
- Chat (matrix + multimedia items)
- Stack Deck
- Publishing
- Feed
- Tasks/Kanban
- Tables
- Github
- Mermaid diagrams
- AI

#### Tech debt

- [ ] #4851
- [x] #4852
- [ ] #4853
- [ ] #4854

#### Documents

- [x] #4855
- [x] #4856
- [x] #4857
- [x] #4858
- [x] #4859

#### Stacks

- [ ] #4860
- [x] #4861
- [ ] #4862
- [x] #4863
- [x] #4864
- [ ] #4865

#### Mobile (bounty)

- [ ] #4866
- [ ] #4867
- [ ] #4868
- [ ] #4869
- [ ] #4870

#### Documents

- [ ] autocomplete when inserting links in documents

#### Cmd + K search

- [ ] fuzzy search cmd+k jump to anything

#### Stacks

- [ ] stacks are folders

#### Comments on things / Chat (bounty)

- [ ] comment threads "about any object"
- [ ] standalone comment threads / channels
- [ ] matrix and discord integration

#### GitHub

- [ ] save-to github (issues, in-tree md files, etc)
- [ ] diff / merge experience for out of sync github issues
- [ ] ensure embedded composer works for github issues

#### Docs

- [ ] DXOS api documentation
- [ ] #3938 
- [ ] Simple samples showcase with all plugins

#### Documents + GitHub

- [ ] turn documents into GitHub issues
- [ ] turn bullets in documents into GitHub issues

#### Chat + GitHub

- [ ] search for messages with a specific reaction
- [ ] turn messages into github issues
- [ ] turn bullets in messages into github issues

#### New dialog

- [ ] input arguments for creating new things

#### Chat + Tables

- [ ] rich mentions of entities in tables
- [ ] turn chats into records
- [ ] attach chats to records

#### Tables

- [ ] sortable columns
- [ ] filterable columns
- [ ] re-order columns
- [ ] tables can run 100s of rows without performance issues

#### Stackystack

- [ ] Stackystack navigation and layout paradigm

#### Tables

- [ ] Data entry forms

#### Tables

- [ ] Kanban with stackystack (e.g.: bounty program tracking scenario)

#### Chat + Content

- [ ] drag a document into a chat to collaborate on it in-thread
- [ ] drag a table into a chat to show a filtered live result in-thread
