### ISSUE TITLE
Scaling ECHO

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#490]
PURPOSE: Initial thoughts on scaling ECHO.

## Background

ECHO databases are made up from replicated hypercore feeds from participating peers. Each feed contains mutations performed by the associated peer. By default the current state of the database is computed from the entire set of feeds for all participants at a particular point (TimeFrame).

Over time, the number of peers and the size of the associated feeds may grow large. Consider 50 peers participating in a Discord like application, running for many months. Typically on startup users want to see the latest messages, but all feeds must be processed first. Consider also a party containing text documents edited by multiple peers over a long time period. During the lifetime of the document it's possible that the majority of the mutations are obsolete (i.e., have been "overwritten") but would still need to be processed to reach the current state.

## Epochs and Snapshots

Periodically, peers could decide (under consensus) to designate a particular TimeFrame as the beginning of a new Epoch and create a snapshot at that point that reifies the state of all state machines into a single file. This file could then be replicated (either using the WebRTC/hypercore or IPFS protocols) and then new mutations applied from this point. New peers joining the party need only "download" the latest snapshot, then receive mutations from this point. This would also reduce the overall storage required by each peer. Further, for applications with extremely frequent mutations, an ECHO Bot could aggressively create new Epochs such that the mutation feeds are relatively transient (say daily).

Peers that fail to join the current Epoch will be considered to have forked the party -- and their mutations would not be considered until they have reverted to the current Epoch.

## Control Feeds

Another optimization would be to have each peer maintain two (or more) feeds per party: one to contain data mutations (high throughput) and another to contain control information, such as credentials and an index of ECHO objects. The control feed could be replicated independently to give the peer a frame of reference for the entire state of the Party. The peer could then selectively request replication of a set of objects -- or just monitor the state of the party membership without receiving the entire data set.

## Branches

@Marik-D's notes from Discord (2021-08-07)

> I did some thinking about ordering. TLDR: timeframes transition echo graph to a model similar to git commit graph. Echo timeframe represents a whole state and is equivalent to a git commit. There could be branches and merge “commits”. If all peers are connected then timeframes will roughly form a single line. If network is partitioned then big branches can appear.  The goal of ordering function is to take that graph and transform it to a linear sequence. A simpler case would be 2 diverging branch tips that share a common base. The ordering function would pick which branch should be rebased on top of another one. To do this we could define a weight for each branch. Height weight “commits” are processed first, and then the lower weight ones. The simplest weight function could be (number of mutations in this branch)*(number of peers that share this branch).This would give advantage to bigger and more active clusters of peers. Bots can have higher weight to account for their always online status. Another idea would be to define weight based on peer’s network connectivity. To prove network connectivity they could include hashes of the most recent DXNS blocks in their feed.

## POC Milestone

- [ ] Gravity test bench simulating N peers randomly mutating (different periodicity).
- [ ] Profiling metric (e.g., startup time).
- [ ] Leadership election (initially statically granted to the originating peer).
- [ ] Periodically write epoch block and generate snapshot.
- [ ] Other peers generate snapshot when processing epoch block.
- [ ] Replicate hypercore feed from given TimeFrame.
- [ ] New peer invitation includes current epoch TimeFrame and synchronizes feeds from this point.
- [ ] Test forking (e.g., peers broadcasting mutations outside of current epoch).
