### ISSUE TITLE
[labs] Rationalize text editors

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4919]
## Phase 1
- [x] Reconcile react-ui-editor TextEditor/MarkdownEditor
- [x] Remove RichText
- [x] Reconcile themes (set defaults).

## Phase 2
- [ ] Reconcile plugin-markdown components (and types)
- [ ] Reconcile useTextModel (w/Dima)
  - [ ] Don't allow return undefined?
- [ ] Replace with BlockNote plugin: https://github.com/dxos/dxos/pull/4908
- [ ] Clean-up MarkdownPlugin (e.g., reconcile EditorMainStandalone vs EditorMainEmbedded)

## PRs
- https://github.com/dxos/dxos/pull/4920

**Comment by jessmartin** [comment]
@richburdon how eminent is phase 2? should we split it into a separate unscheduled issue and close this one out?
