### ISSUE TITLE
[authoring] comments on documents

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5040]
## Product features

- [ ] Show username in comment ( #5323 )
- [ ] Editable comments ( #5161 )
- [ ] Resolve comments (with undo) ( #5162 )
- [ ] Show comments next to stack ( #5324 )

## Low-level

- [x] Storybook: https://github.com/dxos/dxos/pull/5199
- [ ] Preserve comment range/thread when cut/paste.
  - [ ] Detect thread deleted (mark for garbage collection).
- [ ] Focus thread on creation (currently required setTimeout hack.)
- [ ] When selecting a thread, highlight the associated text (scroll to, etc.)
- [x] When selecting a comment range, scroll to the associated thread.
- [x] Delete/resolve thread.
- [x] Button to resolve thread.
- [x] RB: Fix theme/slots for TextEditor (currently applied to container div not cm-scroller).
  - [ ] Would be useful to be able to apply className to `dom` and `scrollerDom` divs.
  - [ ] Scrolling is broken (i.e., doesn't scroll properly in Composer when navigating with the cursor).
  - [ ] Fix gaps between lines with comment bg class (`span` is not as high as `div`)
- [x] Consider how to not require comments to be passed to TextEditor (instead update extension?)
  - i.e., https://github.com/dxos/dxos/pull/5199/files#diff-b00930ab8b3935dc62edbd2f9df9136934286d2c57d50d8c45f260a6fb3a84d5L99

## Story

```bash
pnpm -w nx storybook stories
```

```
http://localhost:9009/iframe.html?args=&id=react-ui-editor-comments--default&viewMode=story
```

https://github.com/dxos/dxos/assets/3523355/695434eb-434b-40d2-9289-7c3b1059bc28

**Comment by marijnh** [comment]
I'm going to try and use this issue to get an understanding of the set of requirements for the comment system. @richburdon, maybe you could answer the questions below and point out where I'm off with my assumptions.

I guess the data model for comments is a set of commented ranges, each with a resolved flag and an array of comment messages.
 - Where are these maintained? I would guess in the CRDT. How do they flow from there into the editor (including updates after the editor has been initialized). Should the editor track them separately as edits happen, or re-sync with the CRDT on every update?
 - Are messages plain text? Or should they also support Markdown?
 - Should deleting the last remaining message in a thread remove the entire comment? Or do we provide some alternative control for that?
 - Is it reasonable to move focus to comment textbox when creating a comment, to make it obvious how to proceed?

The comments are shown in the sidebar. Currently ordered by document position. Focusing one should move the text that it's associated into view (and highlight it) in the editor.
 - Should they align vertically to this text, as in Google Docs?
 - Should they always be visible or only when the commented text is scrolled into view?

What Google docs does is if you copy commented text and paste it back (into the same document), the same comment is associated with both copies. Clipboard integration seems useful when cut-pasting to move text, at least. 
  - Is allowing multiple references to a comment worth the bother? It'd require some kind of id-based data model, and some additional cleverness in the association between text and comment sidebar widgets.
  - We'd have to hook into the editor's copy-paste logic to support this—either by using the HTML clipboard to smuggle metadata into the text, or by keeping side data for the current clipboard content, if it only has to work within a browser tab.

I still see footnote logic (`options.footnote`) in the comment code. What was/is the vision for this? Markdown footnotes have the footnotes in the document itself. That seems at odds with how these comments work—it's inserting an orphan footnote marker without definition. Or is this an entirely different syntax, unrelated to GFM-style footnotes?

**Comment by richburdon** [comment]
Comments are implemented by the posting events (intents) between the Markdown and Thread plugins:

1. The Markdown plugin's comments extension uses a callback to dispatch to the Threads plugin to create a thread: https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-markdown/src/extensions.tsx#L120
2. It also notifies the Thread plugin when a selection is entered or clicked: https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-markdown/src/extensions.tsx#L139; it passes an array of currently visible selections, that includes the currently measured `y` position so that the thread could (it doesn't yet) scroll with the main content.
3. The Thread plugin's CommentsSidebar posts a Focus intent whenever a comment is clicked: https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx#L123; this intent is handled by the Markdown plugin to scroll the associated selection into view: https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx#L43

> Where are these maintained? I would guess in the CRDT. How do they flow from there into the editor (including updates after the editor has been initialized). Should the editor track them separately as edits happen, or re-sync with the CRDT on every update?

The data model for comments is currently described in the Document type: https://github.com/dxos/dxos/blob/main/packages/apps/types/src/proto/schema.proto#L73

Each document maintains an array of Thread objects (which contain message objects) where each Thread (comment stream) is associated with a selection range, which is represented by a serialized string representing the relatively position of the selection anchor and head using the YJS/automerge cursor.

> Are messages plain text? Or should they also support Markdown?

Messages are markdown documents created by the Thread's ChatInput control (https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-thread/src/components/Thread/ChatInput.tsx#L55)

> Should deleting the last remaining message in a thread remove the entire comment? Or do we provide some alternative control for that?

Yes it should. We should also implement a Resolve comment button that would also close the thread. The plumbing for this is pretty straightforward (and under way). Similarly when deleting a range in the text editor, we should detect which comment threads should be deleted.

> Is it reasonable to move focus to comment textbox when creating a comment, to make it obvious how to proceed?

Yes, but in general I don't have a reliable (foolproof) way to set the focus, other than passing a property into the editor: https://github.com/dxos/dxos/blob/main/packages/ui/react-ui-editor/src/components/TextEditor/TextEditor.tsx#L81

> Should they align vertically to this text, as in Google Docs?
> Should they always be visible or only when the commented text is scrolled into view?

It's complicated since the comment threads are managed by a different plugin and are in a different scroll container. Currently both sides scroll into view when the other is clicked. That feels sufficient for this first phase.

> Is allowing multiple references to a comment worth the bother? It'd require some kind of id-based data model, and some additional cleverness in the association between text and comment sidebar widgets.

No, I think just the original selection should reference the comment. But, as you point out we need to track which threads (`id`s) were affected when selections are cut/deleted and then pasted so that the new range can be updated. I think this is actually the main issue to solve for the entire issue.

(Re footnotes: I will remove this soon. I kept it in there since a colleague has implemented exporting documents that contain comments using footnotes.)

**Comment by marijnh** [comment]
> Detect thread deleted (mark for garbage collection).

Is the editor the proper place for this? It seems like it'd be better done at the Automerge-data level—once a comment has no text between its start and end points, it is a candidate to be deleted. But since we'd still want it to survive cut-paste, this cannot be done immediately anyway. I don't know the system well enough to say where the appropriate place for this would be, but I feel it's probably not the editor.

> Fix theme/slots for TextEditor (currently applied to container div not cm-scroller). 

I don't know what this refers to.

> Consider how to not require comments to be passed to TextEditor (instead update extension?) 

Why would that be better? As the data changes (say, a peer client adds a new comment), these need to flow back into the editor. A prop seems reasonable way to do that.

**Comment by marijnh** [comment]
> You had an idea about capturing some additional metadata on cut?

Will it have to work when you cut in one tab and paste in another, or should it work across pages? (It can be less invasive in the first case.)

> so there are gaps between the highlighted rows

The way browsers do this is that line height is determined by the `line-height` style, but the actual height of the inline elements is determined by the font, so it's almost impossible to align those robustly. We could use a [layer](https://codemirror.net/docs/ref/#h_layers) for this, if it bothers you hugely, but that's a bit more expensive, computationally.

> the beauty of the extensions is how they are self-contained.

I see what you mean. But I really appreciate a simple data flow, and separate data channels hidden in extensions tend to make that a lot more messy. Maybe some kind of provision in the editor abstraction for generic prop-based input, that extensions can subscribe to with some custom key, would work. But I'd leave that to someone else, since my React knowledge is pretty shallow.

**Comment by richburdon** [comment]
1. i think we can safely ignore the multi-tab case.

2. thanks for the info. no action required: at this stage just trying to firm up my understanding. (i'm mostly a back-end engineer so a lot of this dom/css is new to me).

3. ok agreed. we've done quite a lot of work with https://www.npmjs.com/package/@deepsignal/react to make ECHO objects reactive (i.e., to the developer you just set/get properties and ECHO handles all of the replication and consistency of the graph). so like you suggest i was thinking about a property abstraction for reactive extensions -- but i think that's for a later stage. i'm quite happy about how relatively simple the current TextEdtior class is given the number of extensions we now have.

**Comment by jessmartin** [comment]
> when deleting a range in the text editor, we should detect which comment threads should be deleted.

From a UX perspective, we probably don't want to actually _delete_ comments that refer to text selections that are no longer present. Rather, we might use something like "Outdated" that GitHub comments do when the file lines change.

![image](https://github.com/dxos/dxos/assets/27258/f4007503-c48b-471e-8cfb-ca65ee349cad)

**Comment by richburdon** [comment]
> From a UX perspective, we probably don't want to actually _delete_ comments that refer to text selections that are no longer present. Rather, we might use something like "Outdated" that GitHub comments do when the file lines change.

Agreed, once we track that a selection has been removed, we can update the data structure to observe this and keep it around until the user explicitly closes the thread (and we can later add a UX control to show closed threads).
