### ISSUE TITLE
Containerize agent

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#5066]
```[tasklist]
### Tasks
- [x] Configure Docker Hub as target
- [x] Refresh Docker Hub branding and documentation
- [ ] https://github.com/dxos/dxos/pull/4985
```

**Comment by nferch** [comment]
https://github.com/dxos/dxos/pull/4985
