### ISSUE TITLE
Agent manager Kubernetes operator and API

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#5067]
```[tasklist]
### Tasks
- [x] Create operator using operator-sdk
- [x] automated deployment to DOKS
- [x] Composer shell API
- [x] expose API to Internet using DOKS LB
- [ ] Configuration of operator
```
