### ISSUE TITLE
[Tracking] DXNS CLI and API lib enhancements and dev support

### ISSUE THREAD

**Issue by wachulski** [dxos/dxos#510]
# CLI
- [ ] Add querying by type or text to CLI fetching resources/types/record (allow to specify dxn instead of cid)
- [x] dxos/protocols#512
- [ ] dxos/protocols#509
- [ ]  Fix typeCid formatting (base58 instead of Array of bytes)
- [x] dxos/protocols#511
- [ ] Align DXNS CLI with org-wide linting policies
- [ ] Update docs (README is outdated at least)
- [ ] Remove services.dxns.schema section

# RegistryApi
- [x] Review by Rich. https://github.com/dxos/dot/pull/214
- [x] dxos/protocols#508
- [x] Address TODOs in https://github.com/dxos/dot/tree/burdon/review
- [x] Address Slight refactoring (likely breaking things?) dxos/dot#182
- [x] Remove api primitive from ApiFactory.createAuctionsApi (int tests that need it can create a separate ApiPromise for that)
- [ ] Remove deprecated fields from protobuf.
- [ ] Improve error msg when registering sth under non-existing domain name
- [ ] Improve domain name validation adding a new domain (regex pattern)
- [ ] Rename `hash -> cid` for ipfs references. 
- [x] dxos/dot#220 
- [ ] dxos/protocols#513
- [x] #514
- [ ] Consider using protobuf definitions in structures returned by the API client

# Hooks library

- [x] Include registry-api in dxos client (@dxos/client) https://github.com/dxos/protocols/pull/516
- [ ] A new lib: Develop DXNS query hooks (conventional react based lib using Registry API client) https://github.com/dxos/protocols/pull/516
    - [x] Can old `registry-client` usage be removed from CLI?
    - [ ] error handling in `setImmediate`
    - [ ] Subscription (or polling) mechanism
    - [ ] Integrate the package into `konsole`
