### ISSUE TITLE
[samples] samples showcase

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5133]
we need to update and expand our samples gallery:
- [ ] [docs] add link to samples to root navigation
- [x] #4641
- [ ] [samples] add chess arena app to samples
- [ ] [samples] turn samples page into a gallery view
- [ ] [samples] add animated previews of each sample
- [ ] [samples] update composer reference in samples gallery
- [ ] [samples] form submit sample
- [ ] [samples] add hello app to samples
- [ ] [samples] coderpad clone app
- [ ] [samples] plugin based sample

List of known samples:
- todos app
- todomvc app
- form submit into echo (does not exist)
- hello app (jess)
- chess app (zaymon)
- coderpad clone app (does not exist)
- 1 more plugin based tbd?
