### ISSUE TITLE
[deck] deck navigation and layout paradigm

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5148]
This is the final chunk of several chunks of work being tackled to move Composer towards [the proposed design](https://www.figma.com/file/w9HsmcQattO4slk9fLWjnh/Operating-system-v1?type=design&node-id=42-479&mode=design&t=GyxcgUrV9mUnrLUA-0). The chunks being layout ( #5237 ), attention ( #5698 ) & deck (this).

The following is a tasklist for implementing in a deck prototype via storybooks. Integration of deck into composer will be a separate task:
```[tasklist]
### Tasks
- [x] horizontal collection of columns
- [x] each column has a header which includes a combined drag handle + actions menu
- [x] columns can be added
- [x] columns can be removed
- [ ] columns other than one can be closed
- [x] columns can be reordered
- [ ] story to demonstrate d&d between columns
- [x] columns can be pinned to either edge of the viewport a sidebar
- [x] keyboard navigation
- [x] columns can be resized
- [x] columns can be made non-removeable
- [x] if columns don't take up the full screen width they should be centered in the viewport
```

**Comment by thure** [comment]
Next: make new layout plugin that uses deck.
