### ISSUE TITLE
[authoring] formatting toolbar

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5345]
- https://github.com/dxos/dxos/issues/5345
- https://github.com/dxos/dxos/pull/5426

## Phase 1

- [x] Toggle emphasis: bold/italic/strong, etc.
- [x] Heading levels.
- [x] Lists: numbered/tasks.
  - [ ] Start list if blank line.
- [x] Insert link: Add `[<selection>]()` around selection.  
- [x] Insert code block 
- [x] Insert simple of table.
  - [ ] Set cursor position (via snippet).
- [x] Update toolbar with current selection state? (e.g., shows heading level of current line?)
- [x] Do not show cursor in readonly mode (or ever show markdown marks).
  - https://github.com/dxos/dxos/issues/5154

## Bugs

- [ ] If select word then select BOLD then ITALIC, clicking ITALIC again adds another level of `*` rather than removing italics.
- [ ] Error adding multiple styles (e.g., bold, then insert, the strike).
  - `Error: Ranges must be added sorted by from position and startSide`

## Phase 2

Integration with react components that can be reused outside of the CM editor:

- [ ] Pick/insert image.
- [ ] Toolbar picker to provide URL.
- [ ] Add comment button
- [ ] link button triggers pop-up to select current page (autocomplete); react integration?
- [ ] menu button to open context menu
- [ ] mention extension to trigger autocomplete when typing `@`
- [ ] toolbar tooltip with callback to render (extensible) toolbar in react

**Comment by wittjosiah** [comment]
Duplicate issue here #5339

**Comment by richburdon** [comment]
Started sketch: https://github.com/dxos/dxos/issues/5345
