### ISSUE TITLE
[authoring] Markdown view/edit mode

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5346]
Duplicate: https://github.com/dxos/dxos/issues/5150

Enable three modes:
- readonly
- source (always show markdown)
- edit (show markdown while actively editing line/context)

## Tasks
- [x] markdown heading extension to show/hide `#` if the cursor is on the same line.
  - https://github.com/dxos/dxos/pull/5389
- [x] consistent option/mode for other extensions (link, table, fenced, etc.)
- [x] inspect perceived rendering latency

**Comment by wittjosiah** [comment]
Noting duplicate issues #5150

**Comment by richburdon** [comment]
Pending general design for editor chrome.
