### ISSUE TITLE
[sdk] ☂️ Indexing

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#5716]
- spec https://composer.dev.dxos.org/8742a33cc5c63a365ac058264208b9b4b331398457521768e97dc7341ca23141

```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/issues/5717
- [ ] https://github.com/dxos/dxos/issues/5718
- [ ] https://github.com/dxos/dxos/issues/5721
- [ ] https://github.com/dxos/dxos/issues/5719
- [ ] https://github.com/dxos/dxos/issues/5720
```
