### ISSUE TITLE
Client protobuf API

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#572]
## Goal

Enable the separation of dxos/client, ECHO, and HALO APIs from the implementation by an RPC boundary. It should be possible to preserve (roughly) the same interface, including:

* Profile management
* Party/device Invitations
* Party management
* Data mutations/state machines
* Queries/Selection API
* Subscriptions (profile, parties, queries, etc.)

## Implementation

- [ ] Document/test environment for RPC mechanism.
- [ ] Document complete client API spec (modules above).
- [ ] Normalize API (see https://github.com/dxos/protocols/blob/main/CHANGELOG.md).
- [ ] Create subset of API (e.g., HALO) used by devtools.
- [ ] Create ECHO sandbox (client/service in-memory/browser) for queries.

### Model serialization

The most complicated part is replicating state machines (models) through the RPC boundary. Current Selection and Database APIs give access to model objects which can be potentially dynamically injected.

S/M already support serialization and snapshotting which allows the S/M state to be serialized, sent across the RPC boundary, and then reconstructed on the side of the client. This would require the backend (that contains client implementation) to have the same set of registering models as the frontend (apps and bots that consume the client API).

When party is opened by the frontend, a subscription to a full set of items in a giving party using `DataService.SubscribeItems` RPC. The subscription would return an array of item metadata. This metadata would be fed into `ItemManager` that would initialize each item and create an individual item data subscription using `SubscribeItemStream` RPC. Mutations made by the frontend to that item would be forwarded using the `DataService.MakeMutation` RPC.

### Subscriptions

Subscriptions are natively supported by @dxos/rpc through `Stream<T>`. Marking protobuf RPC method with a stream response is enough to turn it into a subscription.

### Splitting services

Currently @dxos/rpc only supports a single protobuf service definition per connection. For better modularity we should consider adding support for a dynamic set of services with routing and (potentially) some capability mechanism.

### Profile

```protobuf
service ProfileService {
  rpc SubscribeProfile (google.protobuf.Empty) returns (stream Profile);

  rpc CreateProfile(CreateProfileRequest { displayName }) returns (Profile);
    
  rpc RecoverProfile(RecoverProfileRequest { seedPhrase }) returns (Profile);
    
  rpc CreateHALOInvitation(google.protobuf.Empty) returns (HaloInvitation);
    
  rpc JoinHALO(HaloInvitation) returns (InvitationProcess);
  rpc SubmitInvitationSecret({ InvitationProcess, secret }) returns (Profile);
    
  rpc SubscribeContacts(google.protobuf.Empty) returns (stream Contacts);

  rpc Reset (google.protobuf.Empty) returns (google.protobuf.Empty);
}
```

### Party management

```protobuf
service PartyService {
  rpc SubscribeParties (google.protobuf.Empty) returns (stream SubscribePartiesResponse);

  rpc CreateParty(google.protobuf.Empty) returns(Party);

  rpc CreateInvitation(partyKey) returns (PartyInvitation);

  rpc JoinParty(PartyInvitation) returns (InvitationProcess);
  rpc SubmitInvitationSecret({ InvitationProcess, secret }) returns (Profile);
}
```

### Data management

```protobuf
message ItemDescriptorSet {
  message Item {
    id
    modelDxn
    type
  }
}

message SubscribeItemStreamResponse {
  oneof {
    ItemSnapshot snapshot;
    ItemMutation mutation;
  }
}

service DataService {
  rpc SubscribeItems(partyKey) returns (stream ItemDescriptorSet);

  rpc SubscribeItemStream(partyKey, itemId) returns (stream SubscribeItemStreamResponse);
   
  rpc MakeMutation(EchoMutation) return (MutationReceipt?);

  rpc CreateItem(CreateItemRequest) returns (ItemDescriptor);
}
```

## Tasks

- [x] Add protobufs to protocols package
