### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#580]
# Tasks

- [ ] React bot kit
  - [x] BotFactoryClientProvider
  - [ ] Integration with DXNS
- [ ] Chess demo
- [ ] Bot factory should load its config
- [ ] Persistent bots
- [ ] Metrics/info: 
    - [ ] CPU / RAM usage
    - [ ] Bot container type/info
    - [ ] Metrics from client: parties, networking, mutation/feed count
- [ ] IPFS integration
   - [ ] Loading from IPFS
   - [ ] Publish to IPFS
- [ ] DXNS
  - [ ] Resolve from DXNS
  - [ ] Publish to DXNS
- [ ] Integrate build/publish process with CLI

# Requirements

- Ability to run 100s of bots concurrently (per KUBE)
- Isolation (security, resource management)
- STRETCH: Ability to write bot code in different languages via generated Client protocols APIs bindings

# Spec

- Ability to use Bot framework for network testing (Gravity)
- Bot container ensures isolation of running code and access to host resources (disk, network, etc.)
  - E.g., `isolated-vm`
- Resource monitoring (via console)
- Auto restart bots when host restarts
- Key management and secure storage
- Version management (deploy new bot)
- Life cycle (load from IPFS, start/stop)
- DXNS record/metadata
