### ISSUE TITLE
Improvements to `react-framework`

### ISSUE THREAD

**Issue by rzadp** [dxos/dxos#587]
## Related

- https://github.com/dxos/protocols/issues/583
- https://github.com/dxos/protocols/issues/574

## Goals

- [x] Integrate into Tutorials
    - [ ] Upgrade the text of the tutorial
- [x] Integrate into Braneframe (main app, Text app, etc.)
- [ ] Remove `makeStyles` from all components and use `import { ... } form '@mui/material'`.
- [x] Teamwork is kept alive with working tests.

## TODO

@rzadp 
- [x] Add device invitations to tutorials (unify PartyJoinDialog for both party and device invitations)
    - [x] Use `PartyJoinDialog` and `PartySharingDialog`
    - [x] Implement device invitations https://github.com/dxos/protocols/pull/616
- [ ] Unify device, online, and offline invitations.
- [ ] Error handling (and retries) for invitation flows.
- [x] Port other common braneframe/appkit components to react-framework.
    - [x] Move `RegistrationDialog` (the full one with seed phrase) into `react-framework` https://github.com/dxos/protocols/issues/606
- [x] Make list (below) of components to refactor/move/merge from appkit, react-components, react-framework
- [ ] `DeviceSharing` - add a list of devices, similar to list of members in `PartySharing`
- [ ] Timeout for invitations
- [ ] QR code

@richburdon 
- [x] Move `PartySharingDialog` form Braneframe and rewrite.
- [x] Clean-up `client` invitations APIs (e.g., client.xxx instead of nested calls).
- [x] Remove the deprecated hooks and dialogs.

## TODO

- [x] Rewrite `RedeemDialog`.
- [ ] Have a single `{Registry,Client}Provider`, that either initialises it or just provides it

## Refactor and remove from Appkit

- [x] Fullscreen
- [x] RedeemDialog
- [x] QRCode
- [x] ImportKeyringDialog/ExportKeyringDialog
- [ ] Appkit vs. Framekit?
