### ISSUE TITLE
[agent hosting] log/event management

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#6229]
```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/issues/6228
- [ ] https://github.com/dxos/dxos/issues/6227
- [ ] https://github.com/dxos/eldon-operator/pull/41
```

**Comment by nferch** [comment]
Epic is complete, tracking remaining tasks individually.
