### ISSUE TITLE
[agent hosting] signup flow

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#6257]
Lack of running agent results in yellow ring in shell.

Submission invokes agent hosting platform API which records the identity public key, ToS approval status, and contact info.

After approval, shell calls API to determine whether identity public key is approved for program.
```[tasklist]
### Tasks
- [ ] Enrollment status API
- [ ] Docs page form
- [ ] Approval/email verification flow
- [ ] make sure beta signups can accept a terms of service
```

**Comment by nferch** [comment]
If you're talking specifically about operations against the agent, this was considered, but elected to build something as simple and stupid as possible to serve as scaffolding to permit see how the entire lifecycle works end-to-end.

I would prefer to keep the initial exchange as simple as possible to minimize the complexity of the lifecycle-- that is to keep the container and device join as the same part of the workload lifecycle, but I'm curious what rationale there'd be for separating it?

post-deployment I can see more benefit from re-using dxRPC, which probably doesn't look that different from how we've exposed a websocket.

But the theme of this issue is more around how we manage the flow of the private preview, which I don't think can or should interact with the HALO API.

**Comment by zhenyasav** [comment]
this is now mostly complete or superseded by the cloudflare workers implementation
