### ISSUE TITLE
[agent hosting] instability

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#6307]
many of the DXOS team agents are unstable as per pod restarts:

```NAME                 READY   STATUS               RESTARTS         AGE
pod/04521a16-pod-0   1/1     Running              0                113s
pod/04661fb9-pod-0   0/1     Pending              0                46s
pod/046e7131-pod-0   1/1     Running              8 (5m41s ago)    38m
pod/0474f368-pod-0   1/1     Running              22 (8m44s ago)   3h38m
pod/047d226e-pod-0   0/1     CrashLoopBackOff     9 (69s ago)      55m
pod/048a2e8d-pod-0   0/1     CrashLoopBackOff     7 (2m32s ago)    38m
pod/048dcdbc-pod-0   1/1     Running              0                2m13s
pod/04904f07-pod-0   1/1     Running              0                7h3m
pod/04960a40-pod-0   1/1     Running              0                3d22h
pod/04e4e0f2-pod-0   0/1     PostStartHookError   0                4m12s
pod/04fb5eab-pod-0   1/1     Running              0                3d22h
```

the logs are being flooded with replication errors and `InvariantViolation [Error]: invariant violation: Invalid state
    at failedInvariant (/prod/cli/node_modules/.pnpm/file+packages+common+invariant/node_modules/@dxos/invariant/dist/lib/node/index.cjs:74:9)
    at AutomergeObjectCore.getDoc (/prod/cli/node_modules/.pnpm/file+packages+core+echo+echo-`

```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/issues/6229
- [ ] https://github.com/dxos/dxos/issues/6320
- [ ] https://github.com/dxos/dxos/pull/6304
- [ ] https://github.com/dxos/dxos/pull/6274
- [ ] https://github.com/dxos/eldon-operator/issues/58
```
