### ISSUE TITLE
[agent hosting] dashboard

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6309]
P0
- [ ] how many agents are active (over time)
- [ ] number of unique spaces in total supported by agents (over time)
- [ ] number of unique network connections in total across all agents (over time)

P1
- [ ] number of unique network connections per agent on average (over time) (or a histogram of these)

P3
- [ ] how many agents are 1w inactive (no activity for a week)
- [ ] how many agents are 1mo inactive (no activity for a month)
- [ ] how many agents are over 80% of 1GB disk
- [ ] network traffic
- [ ] some sense of agent uptime?

```[tasklist]
### Tasks
- [ ] https://github.com/dxos/dxos/issues/6355
```
