### ISSUE TITLE
[epic] Berlin Spec

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#6368]
High-level product spec.

## Composer
- [ ] Import/export/migration (aka "credible exit")
- [ ] Comments
  - [ ] Resolve/view/restore resolved comments
- [ ] Stacks
- [ ] View comments across sections
- [ ] Decks
- [ ] Search?
- [ ] Diagrams (TLDraw 2.0)
- [ ] Tables
- [ ] Shell
  - [ ] Address book and direct invitations
- [ ] User feedback?

## SDK/API
- ECHO
  - [ ] Performance and reliability
  - [ ] Stand-alone API
- HALO
  - [ ] Member roles (and revocation)
  - [ ] Direct invitations (from address book)
  - [ ] Delegated admissions (by other peer or agent)
  - [ ] Design spec for local-first auth coalition
- Composer SDK
  - [ ] Preview?

## Agents
- [ ] Deploy on demand (w/credentials)
- [ ] Functions demo

## Ops
- [ ] Beta signup for Composer and Agents 
- [ ] User activity monitoring
- [ ] Logging (systems)
- [ ] Web site refresh (Composer)

**Comment by zhenyasav** [comment]
I think the only things we "need" for berlin are:
- [ ] https://github.com/dxos/devrel/issues/72
- [ ] #6461 
- [ ] https://github.com/dxos/devrel/issues/71
- [ ] https://github.com/dxos/devrel/issues/67
