### ISSUE TITLE
Local-First Conf Expo Day Demo

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#6705]
# Schedule

- SUN
  - [x] Email working end-to-end (mail > CF worker > function > ECHO > inbox plugin) [@richburdon]
- MON
  - [x] Composer Deck working with Table, Sketch, Comments, Inbox (existing) [@ZaymonFC]
  - [x] Composer Status bar (with Devtools perf monitor) [@ZaymonFC]
- TUE
  - [ ] Sync function/trigger objects [@yarolegovich]
  - [ ] GPT plugin responding to email [@richburdon]
- WED
  - [x] Composer Rule editor [@ZaymonFC]
  - [ ] GPT chess hint responding to game move
  - [ ] GPT plugin responding to RAG content [@yarolegovich]
- THU
  - [x] Composer Inbox shows email and responses [@ZaymonFC]
  - [ ] Composer plugins all working with Deck
- FRI
  - [x] Update chess function [@ZaymonFC]
  - [x] Select player in chess UI [@ZaymonFC]
  - [ ] Testing
  - [ ] Demo code snippets

# Tasks

## Protocols [Yaroslav]

- [x] Cloudflare socket protocol (@dxos/w3/packages/hub)
- [x] Functions schema types
- [ ] Function invocation
  - [x] Basic tests 
  - [ ] Pass static context from object
- [ ] Sync function definitions and triggers by space
  - [ ] Register static functions (able to select from Rule UI)
  - [ ] Sync function triggers (rules)
- [x] List functions from CLI
- [x] Basic email worker function
  - [x] Basic function invocation
  - [x] Sync/merge with existing mailbox/messages 
- [x] Update chess function to use same engine as CF worker
- [ ] API issues
  - [ ] Schema registration
  - [ ] Text creation
  - [ ] Object typenames

## Composer [Zaymon]

- [x] New rule editor (adapt Chain/prompt)
  - [x] Storybook for current Chain/prompt editor
  - [x] Stack to create/manage multiple rules
- [ ] Basic Inbox plugin (single column: expand/collapse email)
  - [ ] Key nav up/down.
  - [x] Draft response (change data type); LLM able to add.
  - [ ] Stretch goal to reply/approve LLM answer.
- [ ] Deck functionality
  - [ ] Support for all plugins (below)
- [ ] Presenter

## Troubleshooting

- [x] Fix `dev-server.test.ts` (config functions plugin)
- [x] Fix `chess.test.ts`
- [ ] Fix waiting for space to be ready timeout (CLI) (occasional!)
- [ ] Fix Space invite Composer from CLI. (occasional!)

## Presentation/Assets

- [ ] Diagram (end-to-end)
- [ ] Code samples
  - [ ] Schema
  - [ ] UX
  - [ ] Function

## Plugins:
- [ ] Deck (settings)
- [x] Markdown
- [x] Table
- [x] Sketch (TLDraw 2.0)
- [x] Stack
- [x] Inbox
- [x] Comments
- [x] Chain/Prompt
- [x] Chess
- [x] Thread
- [x] Presenter
- [ ] IPFS/WNFS
- [x] Debug (perf panels)
- [x] Map
- [ ] Stretch: Scripts
- [ ] Stretch: Grid
- [ ] Stretch: Kanban

## Demo script:

- Composer Decks overview
  - Invitations
  - Document/comments collaboration
  - Plugins: Chess
- Functions overview
  - Start CLI
  - Invite to Space
  - Chess function
- Rules
  - Chess LLM suggestion
    - User hint (select schema/history property)
    - Automatic (based on ECHO query)
  - Document lookup
  - Document object extraction (to table)
  - Email trigger
    - Inbox
    - Workflow to answer question
    - Drag PDF to stack (to answer question)

**Comment by richburdon** [comment]
Functions testing

Run tests from `functions`:

```bash
pnpm nx test functions
```

Run demo from `labs-functions`:
Use the local build of the CLI:
```
. $(git rev-parse --show-toplevel)/packages/devtools/cli/scripts/dev.sh
```

Terminal 1:
```bash
# Reset
dx agent stop && dx reset --force && dx halo create testing --no-agent
dx space create --no-agent

# Start agent
dx agent start -f
```

Terminal 2:
```bash
# Start Dev-server
LOG_FILTER="info" dx function dev
```

Terminal 3:
```bash
# Share space
dx space share --open --host https://localhost:
```

**Comment by richburdon** [comment]
https://github.com/dxos/dxos/pull/6721

**Comment by richburdon** [comment]
https://github.com/dxos/dxos/pull/6727 Function dev server and tests

**Comment by jessmartin** [comment]
It happened!
