### ISSUE TITLE
Wallet Extension

### ISSUE THREAD

**Issue by rzadp** [dxos/dxos#68]
# Wallet extension

![Communication](https://github.com/dxos/protocols/raw/main/docs/diagrams/extension-communication.png)

## Components

Wallet extension demo will consist of the following components:

- Background process
    - Holds DXOS profile and data persistently
- Popup page
    - Displays data retrieved from background process
- Content script
    - Injected into a consumer app, allows communication between the app and the extension
- Consumer app
    - Displays data retrieved from the extension through the content script

## Communication

**Stage 1**

- [x] Profile created in background process
- [x] Popup displaying profile data from the extension 
    - [x] Use ports
    - [x] Schema defs for protobuf and compilation
    - [x] Use protobuf encoding & services
    https://developers.google.com/protocol-buffers/docs/proto3#services
    https://protobufjs.github.io/protobuf.js/index.html#using-services
- [x] Consumer app displaying profile data from the extension

**Stage 2**

- [ ] Streaming continious data, i.e. filtered list of items that is changing over time
- [ ] Device invitations
- [ ] Use the new hooks & dialogs created as part of https://github.com/dxos/protocols/issues/587

**Stage 3**

- [ ] Communication between CLI and the extension

**Parallel tasks**

- [ ] Use [InstallInfo](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management/ExtensionInfo) to steer log verbosity
- [ ] Look into disconnection, listener/handler removals, error handling
- [ ] Clear old content scripts when reloading extension (loading a new version)
- [x] Research firefox installation
- [ ] Create chrome store account
- [ ] Script for live-reload
- [ ] Publish the extension as an artifact

## Popup

- [x] Create identity based on seed phrase
- [ ] Reset identity
- [x] Joining a party created in the CLI (`app serve`)
- [x] Figure out a link to open popup in a tab
- [ ] Playwright tests

## The Wallet and the Keyhole

This subprojects aim to allow the user to authenticate into the Keyhole application with his Wallet identity.

**Stage 1**

- [x] ~~Have a piece of application that would communicate with Wallet extension and ask to verify its identity by signing a message~~ Done as a password-like authentication based on public key
    - The message needs a nonce so that the message is one-time use only.
    - The piece of application can be in a playground React app or in Keyhole React app itself.
- [x] Run the Keyhole application using AppServer / Cli-App - without spinning up a Kube
    - [x] Learn about the ties between Keyhole React app, Kube, and Keyhole's `/auth` endpoint.
- [x] Communicate from the application to `/auth` endpoint of Keyhole with the proof of identity from the Wallet
    - [x] Keyhole decides to let the user through or not, based on a list of allowed Public keys
    - [x] Fallback to OTP password (previous mechanism)

At this point, it should be a demonstrable PoC of the new mechanism.

**Stage 2**

- [x] Test interaction of the whole system
    - [ ] Spin up a Kube locally with modified `/auth` mechanism
    - [ ] Deploy a modified Keyhole
    - [ ] Test accessing the local Kube with Wallet
- [ ] Use already existing methods of identity verification from Halo?
    - Needs more research.
- [ ] Iterate on the way Keyhole accepts users - it should accept people in a defined party
    - [x] CLI <-> Extension party invitation
    - [ ] Admitting to Keyhole based on that party
    - [ ] Automate bootstrapping that party when deploying a KUBE

## Useful links

- https://stackoverflow.com/a/13549245
- https://developer.chrome.com/blog/enabling-shared-array-buffer/
