### ISSUE TITLE
Remove automerge-repo from EchoClient

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#6925]
### Preparation

- https://github.com/dxos/dxos/issues/6917
- https://github.com/dxos/dxos/issues/6918

### Design

<img width="1202" alt="image" src="https://github.com/dxos/dxos/assets/35851437/6200f078-625a-4374-9d25-735e5a26ce4d">

```proto
// Aproximate service definition

service QueryService {
  rpc Query({ filter }) returns stream QueryResponse; 
}

service DataSevice {
  rpc Subscribe({ subscriptionId }) returns stream DocumentResponse;

  rpc UpdateSubscription({ addIds, removeIds, subscriptionId }) returns google.protobuf.Empty;
  
  rpc Write({ documentId, change }[]) returns google.protobuf.Empty;
}


```

#### Stage one

- [x] Extend query service to support sync
- [x] Develop & integrate alternative repo impl for the client using sync protocol under similar API as automerge-repo (DocHandle, ...)

#### Stage two

- [ ] Reavaluate AutomergeDb and AutomergeDocLoader classes

TBD

#### Later

- [ ] Reifiend snapshots of objects
