### ISSUE TITLE
CF Demo

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#7758]
## PR

- https://github.com/dxos/dxos/compare/burdon/function-triggers?expand=1

## Tasks

- [ ] Update FunctionPlugin to create triggers
  - [x] NOTE: currently only visible in stack
  - [x] Combo picker should select from published functions
  - [x] When enabled should instantiate local subscription in browser (reuse logic from core/functions)
    -  https://github.com/dxos/dxos/blob/main/packages/core/functions/src/trigger/trigger-registry.ts#L50
  - [ ] Trigger function invocation in TriggerEditor
    -  
  - [ ] Create chess function script
- [ ] make separate browser and node exports for @dxos/functions (or factor out)
- [ ] Script editor; dark background when attended
- [ ] Stretch
  - [ ] Trigger meta property editor
  - [ ] Update ChainPlugin to create prompts
  - [ ] Create GPT function script that imports prompt object
- [ ] Deploy to labs.composer.space

## Demo

https://github.com/user-attachments/assets/11a961f7-caaa-4ebc-84a6-856d3173ef9b

**Comment by richburdon** [comment]
![Image](https://github.com/user-attachments/assets/a627a269-17c8-4451-8394-4495853b061c)
