### ISSUE TITLE
Developer experience: accounts/identity, registration, portal

### ISSUE THREAD

**Issue by egorgripasov** [dxos/dxos#814]
### Requirements

**Accounts / Identity**

- Developer should be able to create and fund a DXNS account
- Developer should be able to store DXNS account(s) in the keyring along with other DXOS keys / accounts.

**DXNS**

- Registration for Developers
  - Multiple keys for different devices?
  - DID?

**KUBE/Console**

- Developer should be able to access KUBE using wallet (and bypass keyhole)
- Developer should be able to see entities he created/registered

**Developer Portal**

- Part of a Console?
- List of developers
- DXNS entities created by any developer.

### Milestones

**Stage 0**

- [x] CLI command to generate & fund DXNS account
  - [x] Generate mnemonic/acc
  - [x] CLI command & KUBE endpoint to increase balance for acc
