### ISSUE TITLE
[tables] Usability tracking issue

### ISSUE THREAD

**Issue by ZaymonFC** [dxos/dxos#8155]
- [x] changing column format causes crash (composer only!?)

  https://github.com/user-attachments/assets/f79e4107-ad93-4d8c-8f22-e75bc5851a4e

- [x] Sidebar overlaps select:
    <img src="https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FMusic-Production%2FMJZtIcVzTo.png?alt=media&token=f839e15e-88b7-4824-94c7-8b7839fa489d" height="200"/>

- [ ] Click column action menu > click column settings > click type select > click somewhere else in the UI ... UI disabled?

  https://github.com/user-attachments/assets/37fbcfe7-2098-4632-b40c-7b7e85387297

- [x] Table not loading in composer on create or page reload (sometimes)
    <img src="https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FMusic-Production%2FWvYY4SbO5b.png?alt=media&token=6e3f6965-562d-42c0-b1d7-c707016c8b4f" height="200"/>

**Comment by thure** [comment]
> click type select > click somewhere else in the UI ... UI disabled
@ZaymonFC if this is using virtual ref, the root of the popper inheritor needs to have `modal={false}` as a prop
