### ISSUE TITLE
[tables] Next

### ISSUE THREAD

**Issue by ZaymonFC** [dxos/dxos#8248]
```[tasklist]
### Tasks
- [ ] Ref cell button to jump to origin table (or row if self reference)
- [x] Create reference row if none exists for value in picker
- [ ] https://github.com/dxos/dxos/issues/8358
- [ ] https://github.com/dxos/dxos/issues/8391
- [ ] https://github.com/dxos/dxos/issues/8359
- [ ] https://github.com/dxos/dxos/issues/8256
- [ ] https://github.com/dxos/dxos/issues/8321
```
