### ISSUE TITLE
Party import & export

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#849]
## Goal

Be able to export a party into a file archive and then import it. Should work in the browser.

## Should resulting party be exact replica (with the same key) or should it be a new party with the same data?

Keeping the same party key would be problematic if the identity importing the party is not one of its members. In that case even though all the data would be there, the party would be in a read-only state and the other peers would not recognize the user that imported the party as a member.

In the event that the user importing the party was a member before (same identity and device keys), theres still a problem. The newly imported party would start syncing with the original one and get the new mutations. This makes it impossible to "branch off" a party in this approach.

## Party cloning

Let's focus on cloning the existing data into a new party with a new key. We cannot do it on the level of feeds, as our new party will need a new `PartyGenesis` message with the new key. We cannot edit the feed messages directly as they are signed and hash-linked.

Moving a level up we have individual feed messages and snapshots. Writing individual ECHO mutations to a new feed won't work since ECHO state machines take the metadata about the author of the message from the feed key that signed the message. Since we re-created the feed, the keys wont match.

Best way to tackle this issue is to re-create echo state from a snapshot. This snapshot will be written to a feed in a special message.

The newly imported party will look like so:

```
// normal party creation messages with a new party key
PartyGenesis(newPartyKey)
KeyAdmit(newIdentity, newPartyKey)
KeyAdmit(newDevice, newIdentity)
IdentitiyInfo(newIdentity)

KeyAdmit(prevIdentity, newPartyKey) // re-signing the previous KeyAdmit message with the new party key
...rest of HALO messages from the dump

SnapshotMessage(DatabaseSnapshot) // full snapshot of the imported party's database
```

This has the following effects:

- The imported party has a new key and the new identity is admitted.
- All of the previous members are still in the party (they can even participate if they know the party key).
- The ECHO data is cloned with a snapshot which preserves the metadata about members who created those mutations.
- The snapshot is written to a feed and can be replicated to other memebers.

## Exported data format

Data will be exported in JSON format (so its readable) that is defined in protobuf.

Backwards compatibility can be verified by commiting snapshot files to the repository periodically and checking that they successfully import in a unit test.

## Tasks
- [x] Exporting party snapshot is already implemented in the API
- [ ] Add "SnapshotMessage" message type to ECHO processor (`ItemDemuxer`).
- [ ] Add `cloneParty(snapshot)` method to the `PartyFactory`.
