### ISSUE TITLE
Bots roadmap

### ISSUE THREAD

**Issue by yivlad** [dxos/dxos#890]
- [x] Add endpoint for querying all available bots (only from dxns?)
- [x] Bot lifecycle
    - [x] List bots 
    - [x] Add methods to bot-factory-client to destroy/start/stop/restart bot.
    - [x] Add the appropriate UI in the console.
    - [x] Add the appropriate UI in the CLI.
- [x] Add endpoints to query logs. 
- [x] Bot UI
    - [x] Spawn bot UI in invite to party dialog.
- [ ] Snapshoting and restoring bots.
  - [x] Implement desired bot state mechanism:
    - [x] Add field `desired state` to bot protobuf schema.
    - [x] Add simple logic to keep the desired state in bot handle. (e.g. on every `update` event check if desired state is the same as actual state and call appropriate methods - `start` or `stop`). When this logic is implemented bot factory should no longer call `start` or `stop` method directly - it should only set the desired state.  
    - [x] Implement restarts bots after critical errors with exponential backoff and maximum retry count.
  - [ ] Snapshot bots - implement mechanism in bot factory which stores `_bot` fields in `BotHandle` to the file system. Next on every start bot factory should read the stored data and restore it's state (create bot handles). This is supposed to deal with possible bot factory critical errors - all bots would be restored after bot factory restart.  
- [ ] Add health check for bots.
  - [ ] Add heartbeat checking from bot factory to specific bot.
  - [ ] Add metrics - CPU, RAM usage, disk usage. Collecting and storing in bot-factory
  - [ ] Add metrics service in bot factory and expose it in bot controller.
  - [ ] Add UI in the console for metrics display. 
  - [ ] Add UI in the CLI for metrics display. 
- [ ] Store bots' clients (`@dxos/client`) objects in bot factory and use Remote Client API in bots. This should allow to use other programming languages for implementing bots.
- [ ] Security.
  - [ ] Restrict bots' access to file system.
  - [ ] Add maximum RAM/CPU/disk usage for a bot.
- [ ] Add more bot containers.
  - [ ] Implement container routing mechanism - which container to use when spawning a bot? Maybe that info should also be published to DXNS alongside IPFS hash?
  - [ ] Implement other bot containers - for instance docker container, which runs a docker image instead of a javascript file.
