### ISSUE TITLE
Multi-party database milestone

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#98]
- [ ] Make sure that snapshots work
- [ ] Extract most of halo stuff #3
  - [ ] Set of active parties
  - [ ] Contacts
- [ ] Reverse Database <-> Party structure #69
  - [ ] Every item must know it's party key
  - [ ] Item manager must work with multiple connecting and disconnecting streams 
  - [ ] Restoring and saving the state of a single party in the items manager
